### ISSUE TITLE
Mail does not get  sent

### ISSUE THREAD

**Issue by sjlcreations** [owncloud/mail#1204]
The app does not want to sent mail

Error	index	Exception: Authenticated ciphertext could not be decoded.

    /home2/natuuren/public_html/newcloud/apps/mail/lib/account.php - line 245: OC\Security\Crypto->decrypt('36a354272f181a1...')
    /home2/natuuren/public_html/newcloud/apps/mail/lib/controller/accountscontroller.php - line 333: OCA\Mail\Account->createTransport()
    [internal function] OCA\Mail\Controller\AccountsController->send(3, NULL, 'test', 'test123', '"John Bekker" <...', '', '', 10, NULL, NULL)
    /home2/natuuren/public_html/newcloud/lib/private/appframework/http/dispatcher.php - line 159: call_user_func_array(Array, Array)
    /home2/natuuren/public_html/newcloud/lib/private/appframework/http/dispatcher.php - line 89: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\AccountsController), 'send')
    /home2/natuuren/public_html/newcloud/lib/private/appframework/app.php - line 108: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\AccountsController), 'send')
    /home2/natuuren/public_html/newcloud/lib/private/appframework/routing/routeactionhandler.php - line 45: OC\AppFramework\App main('AccountsControl...', 'send', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\routing\RouteActionHandler->__invoke(Array)
    /home2/natuuren/public_html/newcloud/lib/private/route/router.php - line 282: call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)
    /home2/natuuren/public_html/newcloud/lib/base.php - line 851: OC\Route\Router->match('/apps/mail/acco...')
    /home2/natuuren/public_html/newcloud/index.php - line 39: OC handleRequest()
    {main}

**Comment by ChristophWurst** [comment]
Hi @sjlcreations,
please fill out the [issue template](https://github.com/owncloud/core/blob/master/issue_template.md), so we can get some more information that might help us debug that error.

Which php version do you use?

**Comment by sjlcreations** [comment]
Steps to reproduce

create an email and click sent


      <https://github.com/owncloud/core/blob/master/issue_template.md#expected-behaviour>Expected
      behaviour

Mail should be sent


      <https://github.com/owncloud/core/blob/master/issue_template.md#actual-behaviour>Actual
      behaviour

Message: Server errror


      <https://github.com/owncloud/core/blob/master/issue_template.md#server-configuration>Server
      configuration

*Operating system*:*linux*

*Web server:Apache Version  2.2.31*

*Database:MySQL Version  5.5.42-37.1-log*

*PHP version: 5.4.24
*

*ownCloud version:**ownCloud*8.2.1 (production)

*Updated from an older ownCloud or fresh install: UPDATED

*

*List of activated apps:*

|If you have access to your command line run e.g.: sudo -u www-data php 
occ app:list from within your ownCloud installation folder |

*The content of config/config.php:*

|If you have access to your command line run e.g.: sudo -u www-data php 
occ config:list system from within your ownCloud installation folder or 
Insert your config.php content here (Without the database password, 
passwordsalt and secret) |

*Are you using external storage, if yes which one:*local/smb/sftp/...

*Are you using encryption:*no

*Are you using an external user-backend, if yes which one:*NO


        <https://github.com/owncloud/core/blob/master/issue_template.md#ldap-configuration-delete-this-part-if-not-used>||Client
        configuration

*Browser: firefox
*

*Operating system: Win 8.1 64bit
*


      <https://github.com/owncloud/core/blob/master/issue_template.md#logs>Logs


        <https://github.com/owncloud/core/blob/master/issue_template.md#web-server-error-log>Web
        server error log

|attached |


        <https://github.com/owncloud/core/blob/master/issue_template.md#owncloud-log-dataowncloudlog>ownCloud
        log (data/owncloud.log)

|attached |


        <https://github.com/owncloud/core/blob/master/issue_template.md#browser-log>Browser
        log

|Insert your browser log here, this could for example include: a) The 
javascript console log b) The network log c) ...|



Op 3-1-2016 om 21:45 schreef Christoph Wurst:

**Comment by ChristophWurst** [comment]
Is this Mail v0.2.1?

Moving to 0.3.1 since it has probably been fixed in 0.3

**Comment by sjlcreations** [comment]
It`s 0.2.1I don´t get the upgrade option to 0.3 where do i get this?

**Comment by ChristophWurst** [comment]
> It`s 0.2.1I don´t get the upgrade option to 0.3 where do i get this?

0.3 will be released soon. We're working on fixing the last few remaining issues: https://github.com/owncloud/mail/issues?q=is%3Aopen+is%3Aissue+milestone%3A%220.3+%E2%80%93+refactoring!%22

**Comment by sjlcreations** [comment]
ok i made a new 8.2.2.2 owncloud testinstall and shall test mail when its available

**Comment by hifigraz** [comment]
Problem still exists in 3.0!

**Comment by ChristophWurst** [comment]
> Problem still exists in 0.3!

@hifigraz thanks for testing. Please fill out the [issue template](https://github.com/owncloud/core/blob/master/issue_template.md) so we get more information about your specific setup. I have never seen that error, so it might only occur on specific platforms or specific providers.

@owncloud/mail any idea?

**Comment by sjlcreations** [comment]
I Installed version 0.3 still does not sent mail, i found this error in the log file
Exception: {"Exception":"Exception","Message":"Authenticated ciphertext could not be decoded.","Code":0,"Trace":"#0 \/home2\/natuuren\/public_html\/newcloud\/apps\/mail\/lib\/account.php(349): OC\\Security\\Crypto->decrypt('36a354272f181a1...')\n#1 \/home2\/natuuren\/public_html\/newcloud\/apps\/mail\/lib\/account.php(171): OCA\\Mail\\Account->createTransport()\n#2 \/home2\/natuuren\/public_html\/newcloud\/apps\/mail\/lib\/controller\/accountscontroller.php(320): OCA\\Mail\\Account->sendMessage(Object(OCA\\Mail\\Model\\Message), 26)\n#3 [internal function]: OCA\\Mail\\Controller\\AccountsController->send(3, NULL, 'test sent mail', 'this is a test ...', 'john@sjlcreatio...', '', '', 26, NULL, NULL)\n#4 \/home2\/natuuren\/public_html\/newcloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#5 \/home2\/natuuren\/public_html\/newcloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Mail\\Controller\\AccountsController), 'send')\n#6 \/home2\/natuuren\/public_html\/newcloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Mail\\Controller\\AccountsController), 'send')\n#7 \/home2\/natuuren\/public_html\/newcloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('AccountsControl...', 'send', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#8 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#9 \/home2\/natuuren\/public_html\/newcloud\/lib\/private\/route\/router.php(291): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#10 \/home2\/natuuren\/public_html\/newcloud\/lib\/base.php(851): OC\\Route\\Router->match('\/apps\/mail\/acco...')\n#11 \/home2\/natuuren\/public_html\/newcloud\/index.php(39): OC::handleRequest()\n#12 {main}","File":"\/home2\/natuuren\/public_html\/newcloud\/lib\/private\/security\/crypto.php","Line":117}	2016-02-18T16:14:53+00:00

Other errors are...
Error	PHP	Array to string conversion at /home2/natuuren/public_html/newcloud/lib/private/template/functions.php#36	2016-02-18T16:11:49+00:00
Error	PHP	Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0

**Comment by ChristophWurst** [comment]
@sjlcreations can you have a look at your database and see if the password is actually encrypted? Credentials are stored in ``oc_mail_accounts``.

Please also provide a ``outbound_password`` as described here: https://github.com/owncloud/mail/issues/720#issuecomment-105664410. Maybe those bugs are related.

**Comment by ChristophWurst** [comment]
I assume you hit the "close" button unintentionally ;-)

**Comment by sjlcreations** [comment]
Both inbound and outbound passwords are encrypted

**Comment by sjlcreations** [comment]
And my passwords are rather short here 9 long

**Comment by ChristophWurst** [comment]
@LukasReschke any idea what might cause this exception to be thrown?

**Comment by ChristophWurst** [comment]
We updated horde libraries in 0.4, maybe that fixed your problems.

**Comment by ChristophWurst** [comment]
no activity in a few months, closing this now. @sjlcreations please  let us know if you still face this problem. Thanks.
