### ISSUE TITLE
Exception: {"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve request! Class request does not exist"

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#1207]
500 while loading unified inbox

Latest nightly

~~~
Fatal 	index 	Exception: {"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve request! Class request does not exist","Code":0,"Trace":"#0 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(98): OC\\AppFramework\\Utility\\SimpleContainer->resolve('request')\n#1 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(59): OC\\AppFramework\\Utility\\SimpleContainer->query('request')\n#2 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(78): OC\\AppFramework\\Utility\\SimpleContainer->buildClass(Object(ReflectionClass))\n#3 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(98): OC\\AppFramework\\Utility\\SimpleContainer->resolve('OCA\\\\Mail\\\\Contro...')\n#4 \/owncloud\/lib\/private\/appframework\/app.php(96): OC\\AppFramework\\Utility\\SimpleContainer->query('OCA\\\\Mail\\\\Contro...')\n#5 \/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('MessagesControl...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#7 \/owncloud\/lib\/private\/route\/router.php(283): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#8 \/owncloud\/lib\/base.php(874): OC\\Route\\Router->match('\/apps\/mail\/acco...')\n#9 \/owncloud\/index.php(48): OC::handleRequest()\n#10 {main}","File":"\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php","Line":84} 	2016-01-06T10:36:41+08:00
Fatal 	index 	Exception: {"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve request! Class request does not exist","Code":0,"Trace":"#0 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(98): OC\\AppFramework\\Utility\\SimpleContainer->resolve('request')\n#1 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(59): OC\\AppFramework\\Utility\\SimpleContainer->query('request')\n#2 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(78): OC\\AppFramework\\Utility\\SimpleContainer->buildClass(Object(ReflectionClass))\n#3 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(98): OC\\AppFramework\\Utility\\SimpleContainer->resolve('OCA\\\\Mail\\\\Contro...')\n#4 \/owncloud\/lib\/private\/appframework\/app.php(96): OC\\AppFramework\\Utility\\SimpleContainer->query('OCA\\\\Mail\\\\Contro...')\n#5 \/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('MessagesControl...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#7 \/owncloud\/lib\/private\/route\/router.php(283): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#8 \/owncloud\/lib\/base.php(874): OC\\Route\\Router->match('\/apps\/mail\/acco...')\n#9 \/owncloud\/index.php(48): OC::handleRequest()\n#10 {main}","File":"\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php","Line":84} 	2016-01-06T10:36:38+08:00
Fatal 	index 	Exception: {"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve request! Class request does not exist","Code":0,"Trace":"#0 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(98): OC\\AppFramework\\Utility\\SimpleContainer->resolve('request')\n#1 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(59): OC\\AppFramework\\Utility\\SimpleContainer->query('request')\n#2 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(78): OC\\AppFramework\\Utility\\SimpleContainer->buildClass(Object(ReflectionClass))\n#3 \/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(98): OC\\AppFramework\\Utility\\SimpleContainer->resolve('OCA\\\\Mail\\\\Contro...')\n#4 \/owncloud\/lib\/private\/appframework\/app.php(96): OC\\AppFramework\\Utility\\SimpleContainer->query('OCA\\\\Mail\\\\Contro...')\n#5 \/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('MessagesControl...', 'show', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#7 \/owncloud\/lib\/private\/route\/router.php(283): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#8 \/owncloud\/lib\/base.php(874): OC\\Route\\Router->match('\/apps\/mail\/acco...')\n#9 \/owncloud\/index.php(48): OC::handleRequest()\n#10 {main}","File":"\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php","Line":84} 	2016-01-06T10:36:38+08:00
~~~

**Comment by ChristophWurst** [comment]
For some weird reason constructor arguments are not resolved as defined in https://github.com/owncloud/mail/blob/master/appinfo/application.php#L89-L102

The issue could be fixed by adding a type hint ``\OCP\IRequest``, but then there are other unresolved dependencies like ``currentUserId`` which simply can't be type-hinted:
https://github.com/owncloud/mail/blob/master/lib/controller/messagescontroller.php#L72-L99

@DeepDiver1975 @owncloud/mail how can we solve this in a clean way? Is this a error in the mail app or in core? For ownCloud > 8.0 registering controllers in ``application.php`` isn't necessary anymore, so we could simply use the ``registerParameter`` for dependencies like ``currentUserId``.

**Comment by ChristophWurst** [comment]
I found out that this issue was introduced with PR #1198. The DI container is not able to resolve ``\OCP\Files\IMimeTypeDetector``, so the exception message is misleading here.

Now I'm not sure if we can solve that problem at all. The way we resolved the mimetype detector before PR #1198 is deprecated and removed in oc9. On the other hand, ``\OC::$server->getMimeTypeDetector()`` can only be used with oc > 8.2 (https://github.com/owncloud/core/blob/ea7fe672e8ef75d7fffc7b9d90eccb82e8e7ad11/lib/public/iservercontainer.php#L442-L448) :confused:

**Comment by ChristophWurst** [comment]
@rullzer any idea how to solve this problem? You're the one who removed deprecated function ;-)

**Comment by rullzer** [comment]
@ChristophWurst well the deprecated functions I removed were private API. So you should not have used them in the first place ;)

But I see that indeed the \OCP\Files\IMimeTypeDetector is missing from the DI class. Let me prepare a PR.

But that does not solve the problem with supporting different versions... I think you have to do some core version dependency hacks there :(

**Comment by ChristophWurst** [comment]
#1218 fixed it for 8.2+, so we still need a fix for 8.1 and lower.

**Comment by PoPoutdoor** [comment]
when will the 8.1 and lower fix land?

**Comment by ChristophWurst** [comment]
> when will the 8.1 and lower fix land?

As soon as someone finds the time to implement it ;-)

**Comment by ChristophWurst** [comment]
> when will the 8.1 and lower fix land?

now: #1247 ;-)
