### ISSUE TITLE
Mail list loading error: »Cannot read property 'setFolderActive' of undefined«

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1280]
Since a few days reading mails doesn’t work anymore for me. I’m on latest code and ran `make optimize-js`. The mail list and detail column show loading spinners.

This is the JS log:
```
Deprecation warning: tipsy is deprecated. Use tooltip instead.
jquery.min.js?v=c3707c643be0fe4e5b764f37fdc8e1f9:6 GET http://localhorst/owncloud/index.php/apps/mail/accounts/-1/folders/YWxsLWluYm94ZXM%3D/messages 500 (Internal Server Error)send @ jquery.min.js?v=c3707c643be0fe4e5b764f37fdc8e1f9:6x.extend.ajax @ jquery.min.js?v=c3707c643be0fe4e5b764f37fdc8e1f9:6fetchMessageList @ communication.js:292loadFolder @ ui.js:243(anonymous function) @ app.js:46triggerEvents @ backbone.js:209Backbone.Events.trigger @ backbone.js:148(anonymous function) @ foldercontroller.js:89c @ jquery.min.js?v=c3707c643be0fe4e5b764f37fdc8e1f9:4p.fireWith @ jquery.min.js?v=c3707c643be0fe4e5b764f37fdc8e1f9:4i.(anonymous function) @ jquery.min.js?v=c3707c643be0fe4e5b764f37fdc8e1f9:4(anonymous function) @ folderservice.js:28c @ jquery.min.js?v=c3707c643be0fe4e5b764f37fdc8e1f9:4p.fireWith @ jquery.min.js?v=c3707c643be0fe4e5b764f37fdc8e1f9:4k @ jquery.min.js?v=c3707c643be0fe4e5b764f37fdc8e1f9:6r @ jquery.min.js?v=c3707c643be0fe4e5b764f37fdc8e1f9:6
ui.js:290 Uncaught TypeError: Cannot read property 'setFolderActive' of undefined
```

And this the owncloud.log:
```
{"reqId":"\/QwRsMge9t0HhUYYIE\/x","remoteAddr":"127.0.0.1","app":"mail","message":"loading messages 0 to 20 of folder <YWxsLWluYm94ZXM=>","level":0,"time":"2016-02-08T15:44:45+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages"}
{"reqId":"\/QwRsMge9t0HhUYYIE\/x","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT c.\\\"carddata\\\" FROM \\\"oc_cards\\\" c WHERE c.\\\"id\\\" IN (SELECT DISTINCT cp.\\\"cardid\\\" FROM \\\"oc_cards_properties\\\" cp WHERE ((cp.\\\"name\\\" = ?) AND (cp.\\\"value\\\" LIKE ?)) AND (cp.\\\"addressbookid\\\" = ?))' with params [\\\"EMAIL\\\", \\\"%ADDRESS-OF-FIRST-EMAIL@example.com%\\\", \\\"1\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1 no such table: oc_cards_properties\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jan\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/home\\\/jan\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT c.\\\"cardd...', Array)\\n#2 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(183): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT c.\\\"cardd...', Array, Array, NULL)\\n#3 \\\/home\\\/jan\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT c.`cardd...', Array, Array)\\n#4 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/db\\\/querybuilder\\\/querybuilder.php(135): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/carddav\\\/carddavbackend.php(755): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/carddav\\\/addressbookimpl.php(85): OCA\\\\DAV\\\\CardDAV\\\\CardDavBackend->search('1', 'ADDRESS-OF-FIRST-EMAIL@...', Array)\\n#7 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/contactsmanager.php(44): OCA\\\\DAV\\\\CardDAV\\\\AddressBookImpl->search('ADDRESS-OF-FIRST-EMAIL@...', Array, Array)\\n#8 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/service\\\/contactsintegration.php(73): OC\\\\ContactsManager->search('ADDRESS-OF-FIRST-EMAIL@...', Array)\\n#9 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/controller\\\/messagescontroller.php(133): OCA\\\\Mail\\\\Service\\\\ContactsIntegration->getPhoto('ADDRESS-OF-FIRST-EMAIL@...')\\n#10 [internal function]: OCA\\\\Mail\\\\Controller\\\\MessagesController->OCA\\\\Mail\\\\Controller\\\\{closure}(Array)\\n#11 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/controller\\\/messagescontroller.php(135): array_map(Object(Closure), Array)\\n#12 [internal function]: OCA\\\\Mail\\\\Controller\\\\MessagesController->index(-1, 'YWxsLWluYm94ZXM...', 0, 20, NULL, NULL)\\n#13 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#14 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\MessagesController), 'index')\\n#15 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\MessagesController), 'index')\\n#16 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('MessagesControl...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#17 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#18 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(273): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#19 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/base.php(856): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#20 \\\/home\\\/jan\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/home\\\/jan\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractSQLiteDriver.php\",\"Line\":58}","level":3,"time":"2016-02-08T15:44:47+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages"}
```

Any idea @ChristophWurst @Gomez @clementhk @ErikPel?

**Comment by ChristophWurst** [comment]
@jancborchardt there's an server error while reading table ``oc_cards_properties``. Hence, I assume contacts is broken in some way and therefore contacts integration breaks the mail app. Can you check if contacts works flawlessly?

**Comment by jancborchardt** [comment]
cc @Henni @DeepDiver1975 on this issue.

But in any case @ChristophWurst Contacts being broken should be caught by us and Mail should still work fine. Or is that not possible?

**Comment by Henni** [comment]
`General error: 1 no such table: oc_cards_properties`
This looks like an issue with the DAV app.
Increasing the version of the DAV app in the info.xml should fix this.

**Comment by jancborchardt** [comment]
@Henni thanks, that fixed it.

Still, shouldn’t we catch these kinds of errors so other apps don’t crash ours, @Gomez @ChristophWurst?

**Comment by ChristophWurst** [comment]
> Still, shouldn’t we catch these kinds of errors so other apps don’t crash ours, @Gomez @ChristophWurst?

We could catch those errors, yes.

**Comment by ChristophWurst** [comment]
However, this would mean every app that uses the contacts manager (we're not using contacts or dav app directly in any way) would have to add that error handling. A more generic approach would be handling errors (catching and logging) in core – e.g. the app simply gets no results when querying contact information but the error is shown in the owncloud log. That way apps consuming the contacts manager will still function.

**Comment by ChristophWurst** [comment]
What should we do?
1. ignore it
2. fix it in the mail app
3. fix it in core

**Comment by jancborchardt** [comment]
If we really want to be stable, we should fix it in core. @ChristophWurst can you open an issue in core with the steps required to do this? It’s not super high priority, but good for stability and we should keep it in mind.

**Comment by ChristophWurst** [comment]
Done: https://github.com/owncloud/core/issues/22661
