### ISSUE TITLE
#1202 Could not resolve OCP\IDb! Class can not be instantiated

### ISSUE THREAD

**Issue by pierreozoux** [owncloud/mail#1283]
Hi!

I wanted to try the newly merged feature #1202  \o/
I used the nightly build of mail app + oC8.2 
is it compatible?
I guess not, I received an error on the command line
```
php ./occ 
An unhandled exception has been thrown:
exception 'OCP\AppFramework\QueryException' with message 'Could not resolve OCP\IDb! Class can not be instantiated' in /var/www/html/lib/private/appframework/utility/simplecontainer.php:87
Stack trace:
#0 /var/www/html/lib/private/appframework/utility/simplecontainer.php(106): OC\AppFramework\Utility\SimpleContainer->resolve('OCP\\IDb')
#1 /var/www/html/lib/private/appframework/utility/simplecontainer.php(66): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IDb')
#2 /var/www/html/lib/private/appframework/utility/simplecontainer.php(85): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#3 /var/www/html/lib/private/appframework/utility/simplecontainer.php(106): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Mail\\Db\\Mai...')
#4 /var/www/html/lib/private/appframework/utility/simplecontainer.php(66): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Mail\\Db\\Mai...')
#5 /var/www/html/lib/private/appframework/utility/simplecontainer.php(85): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#6 /var/www/html/lib/private/appframework/utility/simplecontainer.php(106): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Mail\\Servic...')
#7 /var/www/html/apps/mail/appinfo/register_command.php(14): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Mail\\Servic...')
#8 /var/www/html/lib/private/console/application.php(68): require('/var/www/html/a...')
#9 /var/www/html/console.php(68): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

Could you help here?

Danke!

**Comment by ChristophWurst** [comment]
> is it compatible?

It should be. I'll have a look at this

**Comment by Gomez** [comment]
Fixed https://github.com/owncloud/mail/pull/1353
