### ISSUE TITLE
Error on "Show image" feature

### ISSUE THREAD

**Issue by Gomez** [owncloud/mail#1290]
ownCloud 9.0 beta1 & mail master. 

After pressing "Show images from this sender" i get this error in the log:

```
[Mon Feb 15 15:14:18 2016] Exception: {"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve OCP\\IHelper! Class can not be instantiated","Code":0,"Trace":"#0 \/home\/gomez\/public_html\/mail_dev\/core\/lib\/private\/appframework\/utility\/simplecontainer.php(104): OC\\AppFramework\\Utility\\SimpleContainer->resolve('OCP\\IHelper')\n#1 \/home\/gomez\/public_html\/mail_dev\/core\/lib\/private\/appframework\/utility\/simplecontainer.php(64): OC\\AppFramework\\Utility\\SimpleContainer->query('OCP\\IHelper')\n#2 \/home\/gomez\/public_html\/mail_dev\/core\/lib\/private\/appframework\/utility\/simplecontainer.php(83): OC\\AppFramework\\Utility\\SimpleContainer->buildClass(Object(ReflectionClass))\n#3 \/home\/gomez\/public_html\/mail_dev\/core\/lib\/private\/appframework\/utility\/simplecontainer.php(104): OC\\AppFramework\\Utility\\SimpleContainer->resolve('OCA\\Mail\\Contro...')\n#4 \/home\/gomez\/public_html\/mail_dev\/core\/lib\/private\/appframework\/app.php(97): OC\\AppFramework\\Utility\\SimpleContainer->query('OCA\\Mail\\Contro...')\n#5 \/home\/gomez\/public_html\/mail_dev\/core\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('ProxyController', 'proxy', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#7 \/home\/gomez\/public_html\/mail_dev\/core\/lib\/private\/route\/router.php(273): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#8 \/home\/gomez\/public_html\/mail_dev\/core\/lib\/base.php(856): OC\\Route\\Router->match('\/apps\/mail\/prox...')\n#9 \/home\/gomez\/public_html\/mail_dev\/core\/index.php(39): OC::handleRequest()\n#10 {main}","File":"\/home\/gomez\/public_html\/mail_dev\/core\/lib\/private\/appframework\/utility\/simplecontainer.php","Line":85}
```

@owncloud/mail Can some1 reproduce?

**Comment by Gomez** [comment]
This is still a issues, @jancborchardt You dont get this?

**Comment by ChristophWurst** [comment]
Yes, he does: #1312 ;-)

**Comment by Gomez** [comment]
Fixed: https://github.com/owncloud/mail/pull/1351
