### ISSUE TITLE
Clicking on links doesn’t work, internal server error instead

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1312]
This error is shown instead of the redirect page:
```
Type : OCP\AppFramework\QueryException
Code : 0
Message : Could not resolve OCP\IHelper! Class can not be instantiated
Fichier : /home/jan/owncloud/lib/private/appframework/utility/simplecontainer.php
Ligne : 85

Trace
#0 /home/jan/owncloud/lib/private/appframework/utility/simplecontainer.php(104): OC\AppFramework\Utility\SimpleContainer->resolve('OCP\\IHelper')
#1 /home/jan/owncloud/lib/private/appframework/utility/simplecontainer.php(64): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IHelper')
#2 /home/jan/owncloud/lib/private/appframework/utility/simplecontainer.php(83): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#3 /home/jan/owncloud/lib/private/appframework/utility/simplecontainer.php(104): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Mail\\Contro...')
#4 /home/jan/owncloud/lib/private/appframework/app.php(97): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Mail\\Contro...')
#5 /home/jan/owncloud/lib/private/appframework/routing/routeactionhandler.php(45): OC\AppFramework\App::main('ProxyController', 'redirect', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#6 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)
#7 /home/jan/owncloud/lib/private/route/router.php(273): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)
#8 /home/jan/owncloud/lib/base.php(856): OC\Route\Router->match('/apps/mail/redi...')
#9 /home/jan/owncloud/index.php(39): OC::handleRequest()
#10 {main}
```

Any idea @LukasReschke @ChristophWurst?

**Comment by ChristophWurst** [comment]
which core version is used?

**Comment by jancborchardt** [comment]
Latest master
