### ISSUE TITLE
"Error while loading the selected account"

### ISSUE THREAD

**Issue by qirtaiba** [owncloud/mail#1313]
### Steps to reproduce
1. Create a new account (using same details that work with Thunderbird and iOS amongst others).

### Expected behaviour
See all my email.

### Actual behaviour
"Error while loading the selected account"

**OwnCloud Mail version:** (see ownCloud apps admin page)
0.3.0

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Exim

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
SSL

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
STARTTLS

**Number of accounts:**
1

**ownCloud Mail version build date:** (only if you are using a Nightly Build)
n/a

## ownCloud Core
8.2.2

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.6

**ownCloud version:** (see ownCloud admin page) 8.2.2

**Updated from an older ownCloud or fresh install:** Update

**List of activated apps:** 
```
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - mail: 0.3.0
  - music: 0.3.8
  - notes: 2.0.0
  - tasks: 0.5.1
  - templateeditor: 0.1
Disabled:
  - encryption
  - external
  - notifications
  - provisioning_api
  - search_lucene
  - user_external
  - user_ldapMail, Calendar, Tasks, Gallery
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc1e0d67c158",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.malcolm.id.au"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "3rdpartyroot": "\/var\/www\/owncloud\/",
        "3rdpartyurl": "\/3rdparty",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "php",
        "mail_domain": "malcolm.id.au",
        "mail_from_address": "owncloud",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "preview_libreoffice_path": "\/usr\/bin\/soffice",
        "theme": "",
        "maintenance": false,
        "overwritewebroot": "\/owncloud",
        "overwrite.cli.url": "\/owncloud",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "logfile": "\/var\/log\/owncloud.log",
        "loglevel": "0",
        "trashbin_retention_obligation": "auto"
    }
}
```

### Client configuration
**Browser:** Iceweasel

**Operating system:** Raspbian

#### Web server error log
```
n/a
```

#### ownCloud log (data/owncloud.log)
(Note: for clarity, I removed some of the escaping, which made the log difficult to read.)
```
{"reqId":"F97EQvkudSwAw9/bmR5f","remoteAddr":"192.168.42.113","app":"mail","message":"Setting up manually configured account","level":1,"time":"2016-02-21T19:46:07+00:00","method":"POST","url":"/owncloud/index.php/apps/mail/accounts"}
{"reqId":"F97EQvkudSwAw9/bmR5f","remoteAddr":"192.168.42.113","app":"mail","message":"Connecting to account Jeremy@Malcolm.id.au","level":0,"time":"2016-02-21T19:46:07+00:00","method":"POST","url":"/owncloud/index.php/apps/mail/accounts"}
{"reqId":"F97EQvkudSwAw9/bmR5f","remoteAddr":"192.168.42.113","app":"mail","message":"account created 4","level":0,"time":"2016-02-21T19:46:09+00:00","method":"POST","url":"/owncloud/index.php/apps/mail/accounts"}
{"reqId":"aIHMga7TCocNpj0KX+Bh","remoteAddr":"192.168.42.113","app":"PHP","message":"explode(): Empty delimiter at /var/www/owncloud/apps/mail/lib/mailbox.php#320","level":3,"time":"2016-02-21T19:46:11+00:00","method":"GET","url":"/owncloud/index.php/apps/mail/accounts/4/folders"}
{"reqId":"aIHMga7TCocNpj0KX+Bh","remoteAddr":"192.168.42.113","app":"PHP","message":"array_pop() expects parameter 1 to be array, boolean given at /var/www/owncloud/apps/mail/lib/mailbox.php#321","level":3,"time":"2016-02-21T19:46:11+00:00","method":"GET","url":"/owncloud/index.php/apps/mail/accounts/4/folders"}
{"reqId":"aIHMga7TCocNpj0KX+Bh","remoteAddr":"192.168.42.113","app":"PHP","message":"explode(): Empty delimiter at /var/www/owncloud/apps/mail/lib/mailbox.php#164","level":3,"time":"2016-02-21T19:46:11+00:00","method":"GET","url":"/owncloud/index.php/apps/mail/accounts/4/folders"}
{"reqId":"aIHMga7TCocNpj0KX+Bh","remoteAddr":"192.168.42.113","app":"PHP","message":"explode(): Empty delimiter at /var/www/owncloud/apps/mail/lib/mailbox.php#164","level":3,"time":"2016-02-21T19:46:11+00:00","method":"GET","url":"/owncloud/index.php/apps/mail/accounts/4/folders"}
{"reqId":"aIHMga7TCocNpj0KX+Bh","remoteAddr":"192.168.42.113","app":"index","message":"Exception: {\"Exception\":\"Horde_Imap_Client_Exception_ServerResponse\",\"Message\":\"IMAP error reported by server.\",\"Code\":0,\"Trace\":\"#0 /var/www/owncloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php(4301): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#1 /var/www/owncloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php(4229): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\\n#2 /var/www/owncloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php(1748): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#3 /var/www/owncloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php(1724): Horde_Imap_Client_Socket->_status(Array, 1)\\n#4 /var/www/owncloud/apps/mail/lib/mailbox.php(152): Horde_Imap_Client_Base->status(Object(Horde_Imap_Client_Mailbox), 1)\\n#5 /var/www/owncloud/apps/mail/lib/mailbox.php(159): OCA Mail Mailbox->getStatus(1)\\n#6 /var/www/owncloud/apps/mail/lib/account.php(507): OCA Mail Mailbox->getTotalMessages()\\n#7 /var/www/owncloud/apps/mail/lib/account.php(538): OCA Mail Account->guessBestMailBox(Array)\\n#8 /var/www/owncloud/apps/mail/lib/account.php(376): OCA Mail Account->getSpecialFolder('sent', true)\\n#9 /var/www/owncloud/apps/mail/lib/account.php(572): OCA Mail Account->getSpecialFoldersIds(false)\\n#10 /var/www/owncloud/apps/mail/lib/account.php(303): OCA Mail Account->localizeSpecialMailboxes()\\n#11 /var/www/owncloud/apps/mail/lib/account.php(315): OCA Mail Account->getMailboxes()\\n#12 /var/www/owncloud/apps/mail/lib/controller/folderscontroller.php(61): OCA Mail Account->getListArray()\\n#13 [internal function]: OCA Mail Controller FoldersController->index(4)\\n#14 /var/www/owncloud/lib/private/appframework/http/dispatcher.php(159): call_user_func_array(Array, Array)\\n#15 /var/www/owncloud/lib/private/appframework/http/dispatcher.php(89): OC AppFramework Http Dispatcher->executeController(Object(OCA Mail Controller FoldersController), 'index')\\n#16 /var/www/owncloud/lib/private/appframework/app.php(108): OC AppFramework Http Dispatcher->dispatch(Object(OCA Mail Controller FoldersController), 'index')\\n#17 /var/www/owncloud/lib/private/appframework/routing/routeactionhandler.php(45): OC AppFramework App::main('FoldersControll...', 'index', Object(OC AppFramework DependencyInjection DIContainer), Array)\\n#18 [internal function]: OC AppFramework routing RouteActionHandler->__invoke(Array)\\n#19 /var/www/owncloud/lib/private/route/router.php(291): call_user_func(Object(OC AppFramework routing RouteActionHandler), Array)\\n#20 /var/www/owncloud/lib/base.php(851): OC Route Router->match('/apps/mail/acco...')\\n#21 /var/www/owncloud/index.php(39): OC::handleRequest()\\n#22 {main}\",\"File\":\"/var/www/owncloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php\",\"Line\":4589}","level":3,"time":"2016-02-21T19:46:12+00:00","method":"GET","url":"/owncloud/index.php/apps/mail/accounts/4/folders"}
```

#### Horde log (data/horde.log)
```
------------------------------
>> Sun, 21 Feb 2016 20:14:20 +0000
>> Connection to: imap://mail.malcolm.id.au:993/
>> Server connection took 0.1002 seconds.
S: * OK [CAPABILITY IMAP4REV1 I18NLEVEL=1 LITERAL+ SASL-IR LOGIN-REFERRALS AUTH=PLAIN AUTH=LOGIN] tardis IMAP4rev1 2007e.404 at Sun, 21 Feb 2016 12:14:20 -0800 (PST)
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: terminus)]
S: 1 BAD Missing or invalid argument to AUTHENTICATE
>> Command 1 took 0.0013 seconds.
C: 2 LOGIN terminus [PASSWORD]
S: 2 OK [CAPABILITY IMAP4REV1 I18NLEVEL=1 LITERAL+ IDLE UIDPLUS NAMESPACE CHILDREN MAILBOX-REFERRALS BINARY UNSELECT ESEARCH WITHIN SCAN SORT THREAD=REFERENCES THREAD=ORDEREDSUBJECT MULTIAPPEND] User 
terminus authenticated
>> Command 2 took 0.0178 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 3 LOGOUT
S: * BYE tardis IMAP4rev1 server terminating connection
S: 3 OK LOGOUT completed
>> Command 3 took 0.0032 seconds.
------------------------------
>> Sun, 21 Feb 2016 20:14:23 +0000
>> Connection to: imap://mail.malcolm.id.au:993/
>> Server connection took 0.0791 seconds.
S: * OK [CAPABILITY IMAP4REV1 I18NLEVEL=1 LITERAL+ SASL-IR LOGIN-REFERRALS AUTH=PLAIN AUTH=LOGIN] tardis IMAP4rev1 2007e.404 at Sun, 21 Feb 2016 12:14:23 -0800 (PST)
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: terminus)]
S: 1 BAD Missing or invalid argument to AUTHENTICATE
>> Command 1 took 0.0005 seconds.
C: 2 LOGIN terminus [PASSWORD]
S: 2 OK [CAPABILITY IMAP4REV1 I18NLEVEL=1 LITERAL+ IDLE UIDPLUS NAMESPACE CHILDREN MAILBOX-REFERRALS BINARY UNSELECT ESEARCH WITHIN SCAN SORT THREAD=REFERENCES THREAD=ORDEREDSUBJECT MULTIAPPEND] User 
terminus authenticated
>> Command 2 took 1.424 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
... some parts removed here ...
S: * LIST (\NoInferiors) NIL INBOX
S: 3 OK LIST completed
>> Command 3 took 35.9974 seconds.
C: 4 STATUS mail/sent (MESSAGES)
S: 4 NO Can't open mail/sent: not a selectable mailbox
>> Command 4 took 0.2572 seconds.
C: 5 LOGOUT
S: * BYE tardis IMAP4rev1 server terminating connection
S: 5 OK LOGOUT completed
>> Command 5 took 0.0123 seconds.
```

#### Browser log
```
n/a
```

**Comment by ChristophWurst** [comment]
@qirtaiba please try again with a more recent release of this app, this could be fixed already.

**Comment by qirtaiba** [comment]
I tried with 0.5.2 and I have the same problem. Meanwhile I've started using Rainloop instead which is working fine.
