### ISSUE TITLE
OC9 Exchange 2013 IMAP

### ISSUE THREAD

**Issue by apg1980** [owncloud/mail#1340]
Apache to 2.4.17
PHP to 5.5.29
MySQL to 5.6.25
Ubuntu 14.04
Exchange 2013

I get spinning wheels after creating an account.
The Account is usable if i set again the same account.
Unfortunately i get two configured mail accounts in my settings.
After removing one of the doubles, the spinning wheels appear again.
Any sollutions?

**Comment by ChristophWurst** [comment]
Hi @apg1980,
as you may have noticed, we're using an [issue template](https://github.com/owncloud/mail/blob/master/issue_template.md) to get all the information that is needed to debug this issue. Please use it so we can get more information about your specific setup and webserver/owncloud/horde/browser logs. Thanks.

**Comment by apg1980** [comment]
After adding first credentials following oc log:{"reqId":"L0A5dRIMi9IZmH9bjlas","remoteAddr":"10.10.20.10","app":"mail","message":"Setting up manually configured account","level":1,"time":"2016-03-12T18:34:37+00:00","method":"POST","url":"\/index.php\/apps\/mail\/accounts"}
{"reqId":"L0A5dRIMi9IZmH9bjlas","remoteAddr":"10.10.20.10","app":"mail","message":"Connecting to account <my email address>","level":0,"time":"2016-03-12T18:34:37+00:00","method":"POST","url":"\/index.php\/apps\/mail\/accounts"}
{"reqId":"L0A5dRIMi9IZmH9bjlas","remoteAddr":"10.10.20.10","app":"mail","message":"account created 1","level":0,"time":"2016-03-12T18:34:38+00:00","method":"POST","url":"\/index.php\/apps\/mail\/accounts"}

Now the wheels are spinning.....
I setup the account again:
{"reqId":"Fue8GHr03pfBDcuae0Ns","remoteAddr":"10.10.20.10","app":"mail","message":"account created 2","level":0,"time":"2016-03-12T18:35:47+00:00","method":"POST","url":"\/index.php\/apps\/mail\/accounts"}
{"reqId":"Y8vst0nwimlZ+6Dx5imo","remoteAddr":"10.10.20.10","app":"mail","message":"loading messages 0 to 20 of folder <YWxsLWluYm94ZXM=>","level":0,"time":"2016-03-12T18:35:48+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM=\/messages"}
{"reqId":"1IBdUUSV9QKpnv9DPusY","remoteAddr":"10.10.20.10","app":"index","message":"Exception: {\"Exception\":\"Horde_Imap_Client_Exception_ServerResponse\",\"Message\":\"IMAP error reported by server.\",\"Code\":0,\"Trace\":\"#0 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4301): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#1 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4229): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\\n#2 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(1748): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#3 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(1724): Horde_Imap_Client_Socket->_status(Array, 63)\\n#4 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/lib\\\/account.php(324): Horde_Imap_Client_Base->status(Array)\\n#5 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/lib\\\/controller\\\/folderscontroller.php(61): OCA\\\\Mail\\\\Account->getListArray()\\n#6 [internal function]: OCA\\\\Mail\\\\Controller\\\\FoldersController->index(2)\\n#7 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#8 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#9 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#10 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('FoldersControll...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/route\\\/router.php(273): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#13 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/base.php(873): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#14 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/index.php(39): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":4589}","level":3,"time":"2016-03-12T18:35:50+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/2\/folders"}
{"reqId":"hOwaGWcKhCRFXi7+zMzK","remoteAddr":"10.10.20.10","app":"index","message":"Exception: {\"Exception\":\"Horde_Imap_Client_Exception_ServerResponse\",\"Message\":\"IMAP error reported by server.\",\"Code\":0,\"Trace\":\"#0 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4301): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#1 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4229): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\\n#2 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(1748): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#3 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(1724): Horde_Imap_Client_Socket->_status(Array, 63)\\n#4 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/lib\\\/account.php(324): Horde_Imap_Client_Base->status(Array)\\n#5 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/lib\\\/controller\\\/folderscontroller.php(61): OCA\\\\Mail\\\\Account->getListArray()\\n#6 [internal function]: OCA\\\\Mail\\\\Controller\\\\FoldersController->index(1)\\n#7 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#8 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#9 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#10 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('FoldersControll...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/route\\\/router.php(273): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#13 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/base.php(873): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#14 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/index.php(39): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":4589}","level":3,"time":"2016-03-12T18:35:51+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/1\/folders"}
{"reqId":"Y8vst0nwimlZ+6Dx5imo","remoteAddr":"10.10.20.10","app":"index","message":"Exception: ","level":3,"time":"2016-03-12T18:35:57+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM=\/messages"}

Now i get into no data from my account. This is strange.
In the horde.log are a lot of folders listed with personal names in wont publish. No errors in the log.

**Comment by apg1980** [comment]
No issues with rainloop app on same credentials....

**Comment by ChristophWurst** [comment]
@apg1980 again, please provide the information that is asked in the issue template. It appears to be an IMAP error, like the log entry ``IMAP error reported by server`` says. Hence, the content of horde.log might help identify this bug.

**Comment by ChristophWurst** [comment]
> In the horde.log are a lot of folders listed with personal names in wont publish. No errors in the log.

If you remove sensitive information, you can post it here. Without the information in the IMAP log it's unlikely someone will be able to identify, debug or fix this bug. The exception message is to generic.

**Comment by apg1980** [comment]
this is from the log:

------------------------------
>> Fri, 15 Apr 2016 15:53:25 +0000
>> Connection to: imap://10.10.20.24/
>> Server connection took 0.0027 seconds.
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: 1 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI STARTTLS UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: 1 OK CAPABILITY completed.
>> Command 1 took 0.0072 seconds.
C: 2 [INITIAL CLIENT RESPONSE (username: myusername)]
S: +
C: cC5ncnVuZW5iZXJnAHAuZ3J1bmVuYmVyZwBQYXRhdG9yNDAxNTU3OTkjIw==
S: 2 OK AUTHENTICATE completed.
>> Command 2 took 0.2923 seconds.
C: 3 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI UIDPLUS MOVE ID XPROXY3 CHILDREN IDLE NAMESPACE LITERAL+
S: 3 OK CAPABILITY completed.
>> Command 3 took 0.0042 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 4 LOGOUT
S: * BYE Microsoft Exchange Server 2013 IMAP4 server signing off.
S: 4 OK LOGOUT completed.
>> Command 4 took 0.0019 seconds.

horde.log is not filling up after emptying.

**Comment by apg1980** [comment]
now Spinning wheel after loggin on manually:
>> Fri, 15 Apr 2016 16:24:42 +0000
>> Connection to: imap://10.10.20.24/
>> Server connection took 0.0005 seconds.
S: * OK The Microsoft Exchange IMAP4 service is ready.
C: 1 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI STARTTLS UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+
S: 1 OK CAPABILITY completed.
>> Command 1 took 0.0018 seconds.
C: 2 [INITIAL CLIENT RESPONSE (username: myusername)]
S: +
C: cC5ncnVuZW5iZXJnAHAuZ3J1bmVuYmVyZwBQYXRhdG9yNDAxNTU3OTkjIw==
S: 2 OK AUTHENTICATE completed.
>> Command 2 took 0.1812 seconds.
C: 3 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI UIDPLUS MOVE ID XPROXY3 CHILDREN IDLE NAMESPACE LITERAL+
S: 3 OK CAPABILITY completed.
>> Command 3 took 0.0017 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 4 LIST "" *
S: * LIST (\HasNoChildren) "/" Archive
S: * LIST (\HasNoChildren) "/" Aufgaben
S: * LIST (\Marked \HasNoChildren) "/" Entw&APw-rfe
S: * LIST (\Marked \HasNoChildren) "/" "Gel&APY-schte Elemente"
S: * LIST (\Marked \HasNoChildren) "/" "Gesendete Elemente"
S: * LIST (\HasNoChildren) "/" Journal
S: * LIST (\HasNoChildren) "/" Junk-E-Mail
S: * LIST (\HasNoChildren) "/" Kalender
S: * LIST (\HasChildren) "/" Kontakte
S: * LIST (\HasNoChildren) "/" Notizen
S: * LIST (\HasNoChildren) "/" Postausgang
S: * LIST (\Marked \HasChildren) "/" INBOX
S: * LIST (\Marked \HasChildren) "/" INBOX/@-Archiv
S: * LIST (\HasNoChildren) "/" INBOX/@-Archiv/Bewerbungen
S: * LIST (\HasNoChildren) "/" INBOX/@-Archiv/Dampfen
S: * LIST (\HasNoChildren) "/" INBOX/@-Archiv/GOOGLEMAIL-ALT
S: * LIST (\HasNoChildren) "/" INBOX/@-Archiv/Rezepte
S: * LIST (\HasNoChildren) "/" INBOX/@-Archiv/Riss
S: * LIST (\HasNoChildren) "/" INBOX/@-Archiv/SMS
S: * LIST (\HasNoChildren) "/" INBOX/@-Archiv/Sophos
S: * LIST (\HasNoChildren) "/" INBOX/@-Archiv/Technisches
S: 4 OK LIST completed.
>> Command 4 took 0.0731 seconds.
S: 2 OK AUTHENTICATE completed.
>> Command 2 took 0.173 seconds.
C: 3 CAPABILITY
S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI UIDPLUS MOVE ID XPROXY3 CHILDREN IDLE NAMESPACE LITERAL+
S: 3 OK CAPABILITY completed.
>> Command 3 took 0.0021 seconds.
>> CACHE: Using the OCA\Mail\Cache\Cache storage driver.
C: 4 LIST "" *
>> Command 161 took 1.7276 seconds.
S: 162 NO Server Unavailable. 15
C: 180 LOGOUT
S: * BYE Microsoft Exchange Server 2013 IMAP4 server signing off.
S: 180 OK LOGOUT completed.
>> Command 180 took 0.0078 seconds.

**Comment by apg1980** [comment]
thats the owncloud.log part

{"reqId":"eFkYwf+JwSlYm9gCRt0k","remoteAddr":"10.10.20.10","app":"mail","message":"Setting up manually configured account","level":1,"time":"2016-04-15T18:24:31+02:00","method":"POST","url":"\/index.php\/apps\/mail\/accounts","user":"08598A5C-6FB6-450C-A152-628B33F56156"}
{"reqId":"eFkYwf+JwSlYm9gCRt0k","remoteAddr":"10.10.20.10","app":"mail","message":"Connecting to account mymailaddress","level":0,"time":"2016-04-15T18:24:31+02:00","method":"POST","url":"\/index.php\/apps\/mail\/accounts","user":"08598A5C-6FB6-450C-A152-628B33F56156"}
{"reqId":"eFkYwf+JwSlYm9gCRt0k","remoteAddr":"10.10.20.10","app":"mail","message":"Creating account failed: Mail server denied authentication.","level":3,"time":"2016-04-15T18:24:31+02:00","method":"POST","url":"\/index.php\/apps\/mail\/accounts","user":"08598A5C-6FB6-450C-A152-628B33F56156"}
{"reqId":"w9xWV59D4dQvev3zUpK5","remoteAddr":"10.10.20.10","app":"mail","message":"Setting up manually configured account","level":1,"time":"2016-04-15T18:24:41+02:00","method":"POST","url":"\/index.php\/apps\/mail\/accounts","user":"08598A5C-6FB6-450C-A152-628B33F56156"}
{"reqId":"w9xWV59D4dQvev3zUpK5","remoteAddr":"10.10.20.10","app":"mail","message":"Connecting to account mymailaddress","level":0,"time":"2016-04-15T18:24:41+02:00","method":"POST","url":"\/index.php\/apps\/mail\/accounts","user":"08598A5C-6FB6-450C-A152-628B33F56156"}
{"reqId":"w9xWV59D4dQvev3zUpK5","remoteAddr":"10.10.20.10","app":"mail","message":"account created 4","level":0,"time":"2016-04-15T18:24:41+02:00","method":"POST","url":"\/index.php\/apps\/mail\/accounts","user":"08598A5C-6FB6-450C-A152-628B33F56156"}
{"reqId":"zWoaAeGXWFcOXJ3ciPUZ","remoteAddr":"10.10.20.10","app":"index","message":"Exception: {\"Exception\":\"Horde_Imap_Client_Exception_ServerResponse\",\"Message\":\"IMAP error reported by server.\",\"Code\":0,\"Trace\":\"#0 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4302): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#1 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4230): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\\n#2 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(1749): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#3 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(1726): Horde_Imap_Client_Socket->_status(Array, 63)\\n#4 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/lib\\\/account.php(345): Horde_Imap_Client_Base->status(Array)\\n#5 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/lib\\\/controller\\\/folderscontroller.php(61): OCA\\\\Mail\\\\Account->getListArray()\\n#6 [internal function]: OCA\\\\Mail\\\\Controller\\\\FoldersController->index(4)\\n#7 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#8 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#9 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#10 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('FoldersControll...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/route\\\/router.php(276): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#13 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/base.php(882): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#14 \\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/index.php(39): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/OWNCLOUD-DATA\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":4590}","level":3,"time":"2016-04-15T18:24:45+02:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/4\/folders","user":"08598A5C-6FB6-450C-A152-628B33F56156"}

**Comment by apg1980** [comment]
by the way i am using user_ldap
