### ISSUE TITLE
»Server error« notification but mail is sent

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1368]
I now had several times that there is a »Server error« notification but the mail was sent anyway. Or at least it appears in the »Sent« folder (so it was sent, right?).

The error from the owncloud.log:

```
{"reqId":"Uqiaj23m2JErtYDKDTM7","remoteAddr":"127.0.0.1","app":"mail","message":"collecting 1 email addresses","level":0,"time":"2016-03-24T22:23:56+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/1\/send","user":"jan"}
{"reqId":"Uqiaj23m2JErtYDKDTM7","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT * FROM oc_mail_collected_addresses WHERE \\\"user_id\\\" = ? AND LOWER(email) LIKE LOWER(?) ESCAPE '\\\\'':\\n\\nSQLSTATE[HY000]: General error: 1 no such table: oc_mail_collected_addresses\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jan\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/home\\\/jan\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(785): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT * FROM o...')\\n#2 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(162): Doctrine\\\\DBAL\\\\Connection->prepare('SELECT * FROM o...')\\n#3 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/db\\\/db.php(70): OC\\\\DB\\\\Connection->prepare('SELECT * FROM *...', NULL, NULL)\\n#4 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(232): OC\\\\AppFramework\\\\Db\\\\Db->prepareQuery('SELECT * FROM *...', NULL, NULL)\\n#5 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(320): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('SELECT * FROM *...', Array, NULL, NULL)\\n#6 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/db\\\/collectedaddressmapper.php(49): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntities('SELECT * FROM *...', Array)\\n#7 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/service\\\/autocompletion\\\/addresscollector.php(53): OCA\\\\Mail\\\\Db\\\\CollectedAddressMapper->exists('jan', 'Recipient Name ...')\\n#8 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/controller\\\/accountscontroller.php(330): OCA\\\\Mail\\\\Service\\\\AutoCompletion\\\\AddressCollector->addAddresses(Array)\\n#9 [internal function]: OCA\\\\Mail\\\\Controller\\\\AccountsController->send(1, 'SU5CT1g=', NULL, 'Message text...', '\\\"Recipient Name...', '', '', 1591, '13728', NULL)\\n#10 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#11 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'send')\\n#12 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'send')\\n#13 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('AccountsControl...', 'send', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(277): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#16 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/base.php(871): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#17 \\\/home\\\/jan\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/home\\\/jan\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractSQLiteDriver.php\",\"Line\":58}","level":3,"time":"2016-03-24T22:23:56+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/1\/send","user":"jan"}
{"reqId":"I9vkVPDk\/T+pSGMc3AwC","remoteAddr":"127.0.0.1","app":"mail","message":"Updating draft <1591> in account <1>","level":1,"time":"2016-03-24T22:24:01+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/1\/draft","user":"jan"}

```

**Comment by jancborchardt** [comment]
Another one, the same issue:
```
{"reqId":"2ehfl8u33lTot67bZR\/a","remoteAddr":"127.0.0.1","app":"mail","message":"collecting 4 email addresses","level":0,"time":"2016-03-24T22:32:27+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/3\/send","user":"jan"}
{"reqId":"2ehfl8u33lTot67bZR\/a","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT * FROM oc_mail_collected_addresses WHERE \\\"user_id\\\" = ? AND LOWER(email) LIKE LOWER(?) ESCAPE '\\\\'':\\n\\nSQLSTATE[HY000]: General error: 1 no such table: oc_mail_collected_addresses\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jan\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/home\\\/jan\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(785): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT * FROM o...')\\n#2 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(162): Doctrine\\\\DBAL\\\\Connection->prepare('SELECT * FROM o...')\\n#3 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/db\\\/db.php(70): OC\\\\DB\\\\Connection->prepare('SELECT * FROM *...', NULL, NULL)\\n#4 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(232): OC\\\\AppFramework\\\\Db\\\\Db->prepareQuery('SELECT * FROM *...', NULL, NULL)\\n#5 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/db\\\/mapper.php(320): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('SELECT * FROM *...', Array, NULL, NULL)\\n#6 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/db\\\/collectedaddressmapper.php(49): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntities('SELECT * FROM *...', Array)\\n#7 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/service\\\/autocompletion\\\/addresscollector.php(53): OCA\\\\Mail\\\\Db\\\\CollectedAddressMapper->exists('jan', 'Recipient name...')\\n#8 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/controller\\\/accountscontroller.php(330): OCA\\\\Mail\\\\Service\\\\AutoCompletion\\\\AddressCollector->addAddresses(Array)\\n#9 [internal function]: OCA\\\\Mail\\\\Controller\\\\AccountsController->send(3, 'SU5CT1g=', NULL, 'Message text\\\\xE2\\\\x80\\\\x99s ...', '\\\"Recipient name\\\" <...', '\\\"Recipient 2 name\\\" ...', '', 189, '1517', NULL)\\n#10 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#11 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'send')\\n#12 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'send')\\n#13 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('AccountsControl...', 'send', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(277): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#16 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/base.php(871): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#17 \\\/home\\\/jan\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/home\\\/jan\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractSQLiteDriver.php\",\"Line\":58}","level":3,"time":"2016-03-24T22:32:27+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/3\/send","user":"jan"}
{"reqId":"pMHi9hxhklSUfmGWUAP2","remoteAddr":"127.0.0.1","app":"mail","message":"Updating draft <189> in account <3>","level":1,"time":"2016-03-24T22:32:32+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/3\/draft","user":"jan"}
```

**Comment by ChristophWurst** [comment]
I didn't increment the version number when adding the address collector, hence the migration was not run on that installation because apparently you used the nightly version (or master) before.

Simply run
```
php occ config:app:set mail installed_version --value=0.3.9
```

That should trigger a migration and add the missing table.

**Comment by ChristophWurst** [comment]
The next time we touch the db we should increase the version number to prevent such situations.
