### ISSUE TITLE
Sometimes server error on sending from unified inbox

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#1586]
@ChristophWurst as we talked about, the account ID seems to not be sent so it doesn’t know which account it comes from. Only happens in unified inbox.

**Comment by jancborchardt** [comment]
These are the sent parameters:
![capture du 2016-07-29 15-15-13](https://cloud.githubusercontent.com/assets/925062/17249384/0fb19b16-55a0-11e6-9abe-6df37450e7da.png)


Stacktrace:
```
Type: OCP\AppFramework\Db\DoesNotExistException
	Code: 0
	Message: Did expect one result but found none when executing: query "SELECT * FROM `*PREFIX*mail_accounts` WHERE user_id = ? and id = ?"; parameters Array
(
    [0] => jan
    [1] => 
)
; limit ""; offset ""
File: /home/jan/nextcloud/lib/public/AppFramework/Db/Mapper.php
Line: 289


Trace

#0 /home/jan/nextcloud/lib/public/AppFramework/Db/Mapper.php(373): OCP\AppFramework\Db\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)
#1 /home/jan/nextcloud/apps/mail/lib/db/mailaccountmapper.php(49): OCP\AppFramework\Db\Mapper->findEntity('SELECT * FROM `...', Array)
#2 /home/jan/nextcloud/apps/mail/lib/service/accountservice.php(90): OCA\Mail\Db\MailAccountMapper->find('jan', NULL)
#3 /home/jan/nextcloud/apps/mail/lib/service/unifiedaccount.php(233): OCA\Mail\Service\AccountService->find('jan', NULL)
#4 /home/jan/nextcloud/apps/mail/lib/controller/accountscontroller.php(268): OCA\Mail\Service\UnifiedAccount->resolve('15326')
#5 [internal function]: OCA\Mail\Controller\AccountsController->send(-1, 'YWxsLWluYm94ZXM...', NULL, 'Ah ok, thanks a...', '"Person name" ...', '', '', 0, '15326', NULL)
#6 /home/jan/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(160): call_user_func_array(Array, Array)
#7 /home/jan/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(90): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\AccountsController), 'send')
#8 /home/jan/nextcloud/lib/private/AppFramework/App.php(111): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\AccountsController), 'send')
#9 /home/jan/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\Mail\\Contro...', 'send', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#10 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#11 /home/jan/nextcloud/lib/private/Route/Router.php(293): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#12 /home/jan/nextcloud/lib/base.php(950): OC\Route\Router->match('/apps/mail/acco...')
#13 /home/jan/nextcloud/index.php(40): OC::handleRequest()
#14 {main}
```
