### ISSUE TITLE
Cannot send message

### ISSUE THREAD

**Issue by nikolasES** [owncloud/mail#1626]
### Steps to reproduce
1. Install owncloud mail
2. Login
3. Try to send message - always fails with "server error" message

### Mail app

**Mail app version:** 0.5.2

**Mailserver or service:** citadel

**Transport security - IMAP:** STARTTLS

**Transport security - SMTP:**  STARTTLS

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Version:** (see admin page)

**Updated from an older version or fresh install:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your server installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/owncloud.log or data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/owncloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/owncloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by Gomez** [comment]
Thanks @nikolas-digitalBabylon. Would you complete the issue template. The owncloud.log is needed. Are you using more than one account?

**Comment by nikolas-digitalBabylon** [comment]
Hi,

thanks for responding. I had a look in the owncloud log, after trying to send an email, this entry appears:

Exception: {"Exception":"Exception","Message":"Authenticated ciphertext could not be decoded.","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/mail\/lib\/account.php(370): OC\\Security\\Crypto->decrypt('f16e99ceebc0742...')\n#1 \/var\/www\/owncloud\/apps\/mail\/lib\/account.php(192): OCA\\Mail\\Account->createTransport()\n#2 \/var\/www\/owncloud\/apps\/mail\/lib\/controller\/accountscontroller.php(323): OCA\\Mail\\Account->sendMessage(Object(OCA\\Mail\\Model\\Message), 17847)\n#3 [internal function]: OCA\\Mail\\Controller\\AccountsController->send(1, '', 'test', 'test', '\"Nikolas...', '', '', 17847, NULL, NULL)\n#4 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#5 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Mail\\Controller\\AccountsController), 'send')\n#6 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Mail\\Controller\\AccountsController), 'send')\n#7 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('AccountsControl...', 'send', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#8 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#9 \/var\/www\/owncloud\/lib\/private\/route\/router.php(276): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#10 \/var\/www\/owncloud\/lib\/base.php(882): OC\\Route\\Router->match('\/apps\/mail\/acco...')\n#11 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#12 {main}","File":"\/var\/www\/owncloud\/lib\/private\/security\/crypto.php","Line":118}

I hope this helps

**Comment by ChristophWurst** [comment]
> Authenticated ciphertext could not be decoded.

@LukasReschke I've seen other users report similar bugs. Any idea why that error is thrown while decrypting the account password?

**Comment by ChristophWurst** [comment]
Probably the same bug as #1204

**Comment by nikolas-digitalBabylon** [comment]
It looks similar, yes... I have no access to the server ATM to provide more info. Hopefully there is a way to fix this.

**Comment by ChristophWurst** [comment]
@nikolas-digitalBabylon could you please post your encrypted password, stored in the `oc_mail_accounts` table? Maybe the value is too long and therefore cut off according to @LukasReschke
