### ISSUE TITLE
Error loading HTML mail should be caught earlier

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#170]
Currently when there’s an error loading the HTML mail, there will be a small embedded ownCloud window inside the message.
![image](https://cloud.githubusercontent.com/assets/925062/3844664/2f056c42-1e4b-11e4-811f-fce4fd7dcde0.png)

With this error:
```
[100] Could not open secure TLS connection to the IMAP server.
#0 /home/jan/owncloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php(784): Horde_Imap_Client_Socket->_login()
#1 /home/jan/owncloud/apps/mail/lib/account.php(70): Horde_Imap_Client_Base->login()
#2 /home/jan/owncloud/apps/mail/lib/account.php(96): OCA\Mail\Account->getImapConnection()
#3 /home/jan/owncloud/apps/mail/lib/controller/messagescontroller.php(230): OCA\Mail\Account->getMailbox('INBOX')
#4 /home/jan/owncloud/apps/mail/lib/controller/messagescontroller.php(113): OCA\Mail\Controller\MessagesController->getFolder()
#5 [internal function]: OCA\Mail\Controller\MessagesController->getHtmlBody(4832)
#6 /home/jan/owncloud/lib/private/appframework/http/dispatcher.php(155): call_user_func_array(Array, Array)
#7 /home/jan/owncloud/lib/private/appframework/http/dispatcher.php(84): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\MessagesController), 'getHtmlBody')
#8 /home/jan/owncloud/lib/private/appframework/app.php(57): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\MessagesController), 'getHtmlBody')
#9 /home/jan/owncloud/lib/private/appframework/routing/routeactionhandler.php(44): OC\AppFramework\App::main('MessagesControl...', 'getHtmlBody', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#10 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)
#11 /home/jan/owncloud/lib/private/route/router.php(227): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)
#12 /home/jan/owncloud/lib/base.php(714): OC\Route\Router->match('/apps/mail/acco...')
#13 /home/jan/owncloud/index.php(28): OC::handleRequest()
#14 {main}
```
We need to catch that earlier.

**Comment by jancborchardt** [comment]
I didn’t have this in a long time. Closing.
