### ISSUE TITLE
[oC8] Doesn’t load emails

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/mail#425]
With ownCloud 8, the web interface does not load emails (»Error while loading messages«) and I get this error in the owncloud.log:
```
{"reqId":"ioI64F0dCNUlFmx7hJWq","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {"Message":"IMAP error reported by server.","Code":0,"Trace":"#0 /home/jan/owncloud-dev/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php(4206): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\
#1 /home/jan/owncloud-dev/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php(4136): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\
#2 /home/jan/owncloud-dev/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php(1659): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\
#3 /home/jan/owncloud-dev/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php(1687): Horde_Imap_Client_Socket->_status(Array, 1)\
#4 /home/jan/owncloud-dev/apps/mail/lib/mailbox.php(125): Horde_Imap_Client_Base->status(Object(Horde_Imap_Client_Mailbox), 1)\
#5 /home/jan/owncloud-dev/apps/mail/lib/mailbox.php(129): OCA\Mail\Mailbox->getStatus(1)\
#6 /home/jan/owncloud-dev/apps/mail/lib/mailbox.php(67): OCA\Mail\Mailbox->getTotalMessages()\
#7 /home/jan/owncloud-dev/apps/mail/lib/controller/messagescontroller.php(65): OCA\Mail\Mailbox->getMessages(0, 20)\
#8 [internal function]: OCA\Mail\Controller\MessagesController->index(0, 20)\
#9 /home/jan/owncloud-dev/lib/private/appframework/http/dispatcher.php(158): call_user_func_array(Array, Array)\
#10 /home/jan/owncloud-dev/lib/private/appframework/http/dispatcher.php(86): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\MessagesController), 'index')\
#11 /home/jan/owncloud-dev/lib/private/appframework/app.php(97): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\MessagesController), 'index')\
#12 /home/jan/owncloud-dev/lib/private/appframework/routing/routeactionhandler.php(44): OC\AppFramework\App::main('MessagesControl...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\
#13 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)\
#14 /home/jan/owncloud-dev/lib/private/route/router.php(251): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)\
#15 /home/jan/owncloud-dev/lib/base.php(787): OC\Route\Router->match('/apps/mail/acco...')\
#16 /home/jan/owncloud-dev/index.php(36): OC::handleRequest()\
#17 {main}","File":"/home/jan/owncloud-dev/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php","Line":4488}","level":4,"time":"2015-02-18T20:08:51+00:00"}
```

In the JS error log:
```
jquery.min.js:6
GET http://localhorst/owncloud-dev/index.php/apps/mail/accounts/1/folders/SU5CT1g%253D/messages 500 (Internal Server Error)
jquery.min.js:6 sendjquery.min.js:6
x.extend.ajaxmail.js:229
Mail.UI.loadMessagesmail.js:155
$.ajax.successjquery.min.js:4 c
jquery.min.js:4 p
.fireWithjquery.min.js:6 k
jquery.min.js:6 r
```

Any ideas @DeepDiver1975 @zinks- @PoPoutdoor @Gomez

**Comment by jancborchardt** [comment]
Debugging with @wurstchristoph made it pretty clear that this seems to be a problem with SQLite. (My setup is Ubuntu 14.04, Apache, SQLite)

**Comment by jancborchardt** [comment]
Here’s the relevant IRC log with @wurstchristoph
```
20:31 <christophwu> the client gets all mailboxes. for example my test account only has 'INBOX'
20:31 <christophwu> 'INBOX' is base64 encoded, so it is transfered as 'SU5CT1g='
20:32 <christophwu> BUT, when the client actually requests messages, it uses 'SU5CT1g%253D'
20:32 <christophwu> which equals 'INBOX7' decoded
20:33 <jancborchardt> where does that extra "3D" come from? (I assume %25 is the encoded version of =?)
20:36 <christophwu> oh sorry copied it from FF, it's actually 'SU5CT1g='
20:36 <christophwu> '%25' is url-encoded '='
20:40 <christophwu> jancborchardt: I have found it: https://github.com/owncloud/mail/blob/master/js/mail.js#L231
20:41 <christophwu> I simply removed encodeURIComponent, now the app loads messages
20:42 <christophwu> could you test this? I'm not sure if it is safe to remove...
21:08 <christophwu> jancborchardt: to be precise: the mailbox name is sent to the client as 'SU5CT1g='. the client uses URI encoding, so it becomes 'SU5CT1g%3D'. the server base64 decodes it to 'INBOX7' finally, which is wrong
```
@LukasReschke can you look at that? At least @DeepDiver1975 said you would probably find enjoyment in that. ;D

**Comment by LukasReschke** [comment]
Sure. Official URL encoding expert… I know where the bug is… Let me fix it tomorrow or so (please ping me if I forget it ;D)

**Comment by LukasReschke** [comment]
> IMAP error reported by server

Is an error in PHP 5.6 as far I can tell. It works fine with PHP 5.4 and the [Horde ML](http://horde.690.n7.nabble.com/Imp-LDAP-Error-listMailboxes-IMAP-error-reported-by-server-td130533.html) led me to https://bugs.php.net/bug.php?id=68948

So for now users have to use PHP 5.4 - 5.6, the other JS errors are though still valid. On it :see_no_evil:

**Comment by wurstchristoph** [comment]
In case this helps fixing: I have tried to debug the issue using wireshark. I found out that the actual IMAP request is

    2 STATUS INBOX7 (MESSAGES)

although the mailbox name is ``INBOX``. This causes the server to respond

    2 NO Mailbox doesn't exit: INBOX7

which throws an ``IMAP error reported by server`` exception in Horde.

**Comment by jancborchardt** [comment]
Thank you @LukasReschke and @wurstchristoph for fixing this! :)
