### ISSUE TITLE
Resetting the app doesn't remove the registered accounts.

### ISSUE THREAD

**Issue by Henni** [owncloud/mail#519]
I executed the commands:
```sql
DELETE FROM oc_appconfig WHERE appid = 'mail';
DROP TABLE oc_mail_accounts;
```
as described in the README to reset my mail app installation.

But somehow my registered mail account was kept after reenabling the app. It seems that it is cached somewhere outside of the database. Even restarting apache didn't help.

Additionally the following Exception is logged:
```
Exception: {"Message":"No matching entry found","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/public\/appframework\/db\/mapper.php(290): OCP\\AppFramework\\Db\\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)\n#1 \/var\/www\/owncloud\/apps\/mail\/lib\/db\/mailaccountmapper.php(44): OCP\\AppFramework\\Db\\Mapper->findEntity('SELECT * FROM `...', Array)\n#2 \/var\/www\/owncloud\/apps\/mail\/lib\/controller\/messagescontroller.php(262): OCA\\Mail\\Db\\MailAccountMapper->find('hendrik', '1')\n#3 \/var\/www\/owncloud\/apps\/mail\/lib\/controller\/messagescontroller.php(270): OCA\\Mail\\Controller\\MessagesController->getAccount()\n#4 \/var\/www\/owncloud\/apps\/mail\/lib\/controller\/messagescontroller.php(87): OCA\\Mail\\Controller\\MessagesController->getFolder()\n#5 [internal function]: OCA\\Mail\\Controller\\MessagesController->index(0, 20, NULL)\n#6 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(158): call_user_func_array(Array, Array)\n#7 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(86): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Mail\\Controller\\MessagesController), 'index')\n#8 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Mail\\Controller\\MessagesController), 'index')\n#9 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('MessagesControl...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#11 \/var\/www\/owncloud\/lib\/private\/route\/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#12 \/var\/www\/owncloud\/lib\/base.php(767): OC\\Route\\Router->match('\/apps\/mail\/acco...')\n#13 \/var\/www\/owncloud\/index.php(36): OC::handleRequest()\n#14 {main}","File":"\/var\/www\/owncloud\/lib\/public\/appframework\/db\/mapper.php","Line":234}
```

How do I remove this registered mail account?
And why isn't it removed by dropping the oc_mail_accounts table?

**Comment by jancborchardt** [comment]
@DeepDiver1975 probably this has to do with the new account & folder caching introduced in #501?

**Comment by jancborchardt** [comment]
I can reproduce this: Even just removing an account from the settings doesn’t remove it from the sidebar. This most definitely has something to do with the caching #501. cc @DeepDiver1975

**Comment by LEDfan** [comment]
AFAIK this is cached in the LocalStorage of the browser. You can clear this by opening the JS console and run `localStorage.clear()`

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 probably this has to do with the new account & folder caching introduced in #501?

yes - this needs some more love - I had issues with the cache in #522 as well
