### ISSUE TITLE
No mails shown - but the folders

### ISSUE THREAD

**Issue by Gomez** [owncloud/mail#551]
Installed mail master on oC 8.0.2. Done manual mail config, connection works but no mail appears:
 
![](http://steffen-lindner.de/temp/mail_app.png)

Log if i click on Posteingang:
```
{"reqId":"bc8936d14c71b854f760933dbde96ea4","remoteAddr":"192.168.1.101","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-04-29T09:32:05+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/3\/folders\/SU5CT1g=\/messages"}
{"reqId":"bc8936d14c71b854f760933dbde96ea4","remoteAddr":"192.168.1.101","app":"mail","message":"loading messages 0 to 20 of folder <INBOX>","level":0,"time":"2015-04-29T09:32:05+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/3\/folders\/SU5CT1g=\/messages"}
```
Log if i click on Gesendet:
```
{"reqId":"d6d2d6ccfbb86fd602bfade09d0cdfec","remoteAddr":"192.168.1.101","app":"mail","message":"loading messages 0 to 20 of folder <Sent>","level":0,"time":"2015-04-29T09:32:49+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/3\/folders\/U2VudA==\/messages"}
{"reqId":"d6d2d6ccfbb86fd602bfade09d0cdfec","remoteAddr":"192.168.1.101","app":"index","message":"Exception: {\"Message\":\"Could not open mailbox \\\"Sent\\\".\",\"Code\":200,\"Trace\":\"#0 \\\/var\\\/www\\\/virtual\\\/cloud.portknox.net\\\/htdocs\\\/apps2\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(1042): Horde_Imap_Client_Socket->_openMailbox(Object(Horde_Imap_Client_Mailbox), 1)\\n#1 \\\/var\\\/www\\\/virtual\\\/cloud.portknox.net\\\/htdocs\\\/apps2\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(2202): Horde_Imap_Client_Base->openMailbox(Object(Horde_Imap_Client_Mailbox), 3)\\n#2 \\\/var\\\/www\\\/virtual\\\/cloud.portknox.net\\\/htdocs\\\/apps2\\\/mail\\\/lib\\\/mailbox.php(77): Horde_Imap_Client_Base->search(Object(Horde_Imap_Client_Mailbox), Object(Horde_Imap_Client_Search_Query), Array)\\n#3 \\\/var\\\/www\\\/virtual\\\/cloud.portknox.net\\\/htdocs\\\/apps2\\\/mail\\\/lib\\\/controller\\\/messagescontroller.php(92): OCA\\\\Mail\\\\Mailbox->getMessages(0, 21, NULL)\\n#4 [internal function]: OCA\\\\Mail\\\\Controller\\\\MessagesController->index(0, 20, NULL)\\n#5 \\\/var\\\/www\\\/virtual\\\/cloud.portknox.net\\\/htdocs\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/virtual\\\/cloud.portknox.net\\\/htdocs\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\MessagesController), 'index')\\n#7 \\\/var\\\/www\\\/virtual\\\/cloud.portknox.net\\\/htdocs\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\MessagesController), 'index')\\n#8 \\\/var\\\/www\\\/virtual\\\/cloud.portknox.net\\\/htdocs\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('MessagesControl...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/var\\\/www\\\/virtual\\\/cloud.portknox.net\\\/htdocs\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#11 \\\/var\\\/www\\\/virtual\\\/cloud.portknox.net\\\/htdocs\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#12 \\\/var\\\/www\\\/virtual\\\/cloud.portknox.net\\\/htdocs\\\/index.php(36): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/cloud.portknox.net\\\/htdocs\\\/apps2\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":1146}","level":4,"time":"2015-04-29T09:32:49+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/3\/folders\/U2VudA==\/messages"}
```

**Comment by Xenopathic** [comment]
Could you enable IMAP backend logging (`'app.mail.imaplog.enabled' => true` in config.php) and post the command stream here? There'll be lots of output - you will want to pick out the relevant section.

**Comment by Gomez** [comment]
These are the last lines after a click on "Inbox":

```
S: * 94 FETCH (UID 278801 ENVELOPE ("Wed, 29 Apr 2015 01:40:29 -0700" "Re: [training] Fix typos and small issues after proofreading units 0, 1 and 2. (#64)" (("Gil Forcada Codinachs" NIL "notifications" "github.com")) (("Gil Forcada Codinachs" NIL "notifications" "github.com")) (("plone/training" NIL "reply+0000be54b6e435ae700b29feec5193f5e257437fefefe79592cf0000000111585afd92a169ce0442a500" "reply.github.com")) (("plone/training" NIL "training" "noreply.github.com")) NIL NIL "<plone/training/pull/64@github.com>" "<plone/training/pull/64/c97352903@github.com>") FLAGS (\Seen \Deleted NonJunk) RFC822.SIZE 4327 INTERNALDATE "29-Apr-2015 08:40:33 +0000" BODYSTRUCTURE (("text" "plain" ("charset" "utf-8") NIL NIL "7bit" 243 4 NIL NIL NIL)("text" "html" ("charset" "utf-8") NIL NIL "7bit" 945 10 NIL NIL NIL) "alternative" ("boundary" "--==_mimepart_554098fdb0d25_f973fa46d9692bc4830e7" "charset" "utf-8") NIL NIL) BODY[HEADER.FIELDS ("IMPORTANCE" "LIST-POST" "X-PRIORITY" "CONTENT-TYPE")] {249}
S: [LITERAL DATA: 249 bytes]
S: )
S: * 95 FETCH (UID 278802 ENVELOPE ("Wed, 29 Apr 2015 01:45:36 -0700" "Re: [training] Fix typos and small issues after proofreading units 0, 1 and 2. (#64)" (("sven" NIL "notifications" "github.com")) (("sven" NIL "notifications" "github.com")) (("plone/training" NIL "reply+0000be543f185780cafee4a53ec6c97b832594a2819460ff92cf000000011158* BYE [ALERT] Fatal error: Invalid argument
>> ERROR: Server closed the connection.
```

Mail #95 was already deleted. 

We got the same error ages ago, but probably never fixed it. I can workaround it if i switch to thunderbird, click on the account and execute "compact". Now i can see my mail in oc mail until ...

**Comment by jancborchardt** [comment]
(Sidenote: Why is are there two »Sent mail« folders? Just testing, or a bug on our side?)

**Comment by Gomez** [comment]
@jancborchardt  On my side. I had two send folders (Created by a other mail client, i think)

@Xenopathic Something i can help ( i can create a test email account if needed)? The app is not use-able for me (probably others too)

**Comment by jancborchardt** [comment]
@Gomez which provider is that? And yeah, best create a test mail account and give the credentials to @Xenopathic and @DeepDiver1975

**Comment by clementhk** [comment]
I'd also like to have a test account only if it's not too much trouble as I'm just interested of knowing what you're facing.

**Comment by jancborchardt** [comment]
@gomez moving to 0.2 since this is likely some specific issue with your setup. If you want it to be fixed faster, you need to supply test accounts to folks like @DeepDiver1975 @clementhk @wurstchristoph @Xenopathic ;)

**Comment by Xenopathic** [comment]
@Gomez Feel free to send the details via email :smile:

**Comment by DeepDiver1975** [comment]
@Gomez did you fetch latest horde libs by running composer install?

**Comment by Gomez** [comment]
Will do @Xenopathic. Need some time. Milestone 0.2 is fine for me.

**Comment by Gomez** [comment]
So, i replaced courier with dovecot mail server and now everything works :) 
You guys created a nice mail app ;) Happy i can use mail app now more often.

**Comment by jancborchardt** [comment]
Hehehehe – nice to hear it works now.
