### ISSUE TITLE
Delete "Favorites" message not working

### ISSUE THREAD

**Issue by wurstchristoph** [owncloud/mail#553]
Messages in the favorites folder cannot be deleted. 

owncloud.log says ```Could not open mailbox "INBOX/FLAGGED"```

Horde log:
```
------------------------------
>> Wed, 29 Apr 2015 12:50:22 +0000
>> Connection to: imap://imap.world4you.com/
>> Server connection took 0.01 seconds.
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: xxx@yyy.at)]
S: 1 OK [CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA CHILDREN ID] Logged in
>> Command 1 took 0.0499 seconds.
C: 2 LIST "" *
S: * LIST (\HasNoChildren) "." "test folder"
S: * LIST (\HasNoChildren) "." "testfolder2"
S: * LIST (\HasNoChildren) "." "Sent"
S: * LIST (\HasNoChildren) "." "Drafts"
S: * LIST (\HasNoChildren) "." "Trash"
S: * LIST (\HasNoChildren) "." "INBOX"
S: 2 OK List completed.
>> Command 2 took 0.0091 seconds.
C: 3 STATUS INBOX (MESSAGES)
S: * STATUS "INBOX" (MESSAGES 123)
S: 3 OK Status completed.
>> Command 3 took 0.0094 seconds.
C: 4 STATUS INBOX (MESSAGES)
S: * STATUS "INBOX" (MESSAGES 123)
S: 4 OK Status completed.
>> Command 4 took 0.0103 seconds.
C: 5 STATUS Sent (MESSAGES)
S: * STATUS "Sent" (MESSAGES 93)
S: 5 OK Status completed.
>> Command 5 took 0.0089 seconds.
C: 6 STATUS Sent (MESSAGES)
S: * STATUS "Sent" (MESSAGES 93)
S: 6 OK Status completed.
>> Command 6 took 0.0089 seconds.
C: 7 STATUS Drafts (MESSAGES)
S: * STATUS "Drafts" (MESSAGES 5)
S: 7 OK Status completed.
>> Command 7 took 0.01 seconds.
C: 8 STATUS Drafts (MESSAGES)
S: * STATUS "Drafts" (MESSAGES 5)
S: 8 OK Status completed.
>> Command 8 took 0.0091 seconds.
C: 9 STATUS Trash (MESSAGES)
S: * STATUS "Trash" (MESSAGES 66)
S: 9 OK Status completed.
>> Command 9 took 0.0086 seconds.
C: 10 STATUS Trash (MESSAGES)
S: * STATUS "Trash" (MESSAGES 66)
S: 10 OK Status completed.
>> Command 10 took 0.0104 seconds.
C: 11 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: * STATUS "INBOX" (MESSAGES 123 RECENT 0 UIDNEXT 168 UIDVALIDITY 1428599115 UNSEEN 0)
S: 11 OK Status completed.
>> Command 11 took 0.0098 seconds.
C: 12 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: * STATUS "INBOX" (MESSAGES 123 RECENT 0 UIDNEXT 168 UIDVALIDITY 1428599115 UNSEEN 0)
S: 12 OK Status completed.
>> Command 12 took 0.0096 seconds.
C: 13 STATUS Trash (MESSAGES)
S: * STATUS "Trash" (MESSAGES 66)
S: 13 OK Status completed.
>> Command 13 took 0.0096 seconds.
C: 14 STATUS Trash (MESSAGES)
S: * STATUS "Trash" (MESSAGES 66)
S: 14 OK Status completed.
>> Command 14 took 0.01 seconds.
C: 15 SELECT INBOX/FLAGGED
S: 15 NO Invalid mailbox name: INBOX/FLAGGED
>> Command 15 took 0.0091 seconds.
C: 16 LOGOUT
S: * BYE Logging out
S: 16 OK Logout completed.
>> Command 16 took 0.0085 seconds.
```

**Comment by jancborchardt** [comment]
Can confirm. JS console:
```
DELETE http://localhorst/owncloud/index.php/apps/mail/accounts/17/folders/SU5CT1gvRkxBR0dFRA%3D%3D/messages/8824 500 (Internal Server Error)
```
horde.log
```
------------------------------
>> Wed, 29 Apr 2015 16:32:37 +0000
>> Connection to: imap://example.com
>> Server connection took 0.3898 seconds.
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN] Dovecot ready.
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: user@example.com)]
S: 1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS MULTIAPPEND UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS SPECIAL-USE QUOTA] Logged in
>> Command 1 took 0.176 seconds.
C: 2 LIST () "" (*) RETURN (SPECIAL-USE)
S: * LIST () "/" "Trash"
S: * LIST () "/" "Trash/Test subfolder"
S: * LIST () "/" "INBOX"
S: * LIST () "/" "Sent"
S: * LIST () "/" "Junk"
S: * LIST () "/" "Drafts"
S: 2 OK List completed.
>> Command 2 took 0.1047 seconds.
C: 3 SELECT INBOX/FLAGGED
S: 3 NO Mailbox doesn't exist: INBOX/FLAGGED
>> Command 3 took 0.1016 seconds.
C: 4 LOGOUT
S: * BYE Logging out
S: 4 OK Logout completed.
>> Command 4 took 0.1018 seconds.
```
owncloud.log
```
{"reqId":"nzCd670qrzMKTYDVrqsl","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"Horde_Imap_Client_Exception\",\"Message\":\"Could not open mailbox \\\"INBOX\\\/FLAGGED\\\".\",\"Code\":200,\"Trace\":\"#0 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(1005): Horde_Imap_Client_Socket->_openMailbox(Object(Horde_Imap_Client_Mailbox), 2)\\n#1 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(2892): Horde_Imap_Client_Base->openMailbox(Object(Horde_Imap_Client_Mailbox), 2)\\n#2 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(296): Horde_Imap_Client_Base->copy(Object(Horde_Imap_Client_Mailbox), Object(Horde_Imap_Client_Mailbox), Array)\\n#3 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/controller\\\/messagescontroller.php(247): OCA\\\\Mail\\\\Account->deleteMessage('INBOX\\\/FLAGGED', 8824)\\n#4 [internal function]: OCA\\\\Mail\\\\Controller\\\\MessagesController->destroy(8824)\\n#5 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#6 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\MessagesController), 'destroy')\\n#7 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(104): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\MessagesController), 'destroy')\\n#8 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('MessagesControl...', 'destroy', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#11 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/base.php(853): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#12 \\\/home\\\/jan\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/home\\\/jan\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":1149}","level":4,"time":"2015-04-29T16:32:38+00:00","method":"DELETE","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/17\/folders\/SU5CT1gvRkxBR0dFRA%3D%3D\/messages\/8824"}
```

@DeepDiver1975 @Xenopathic @LukasReschke any idea?

**Comment by DeepDiver1975** [comment]
That inbox/flagged is a special folder - no imap folder.  I will take care of this ....
