### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by LEDfan** [owncloud/mail#627]
Looks like the mail app doesn't like my mail sever :smiley: It had worked for some time now, but now it's broken. again. 

### Steps to reproduce
1. Load the Mail app 

### Expected behaviour
Account and mails are loaded

### Actual behaviour
A yellow error opens "Error while loading the selected account`

### Server configuration
**Operating system**:
Centos 7

**Web server:**
Apache 2.4

**Database:**
`mysql  Ver 15.1 Distrib 5.5.41-MariaDB, for Linux (x86_64) using readline 5.1` 

**PHP version:**
````
PHP 5.6.6 (cli) (built: Feb 19 2015 20:49:15) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with XCache v3.2.0, Copyright (c) 2005-2014, by mOo
    with XCache Cacher v3.2.0, Copyright (c) 2005-2014, by mOo
````

**ownCloud version:** 
ownCloud 8.1 alpha 3 

**Updated from an older ownCloud or fresh install:** 
ownCloud 8.0.2

**List of activated apps:**
 - Mail
 - Files
 - Contacts
 - Calendar

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => 
  'app.mail.imaplog.enabled' => true,
  'passwordsalt' => 
  'trusted_domains' => 
  array (
    0 => 'xx'
  ),
  'datadirectory' => '/srv/xx/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.4',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'secret' => 'xxx',
  'forcessl' => true,
  'asset-pipeline.enabled' => true,
);
```

**Are you using external storage, if yes which one:** webdav + owncloud
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no.

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VUn225Uv239iO37JggIQCQAAAAk","remoteAddr":"81.82.127.90","app":"index","message":"Exception: {\"Exception\":\"Horde_Imap_Client_Exception_ServerResponse\",\"Message\":\"The object could not be deleted because it does not exist.\",\"Code\":23,\"Trace\":\"#0 \\\/srv\\\/xxx\\\/www\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4447): Horde_Imap_Client_Socket->_responseCode(Object(Horde_Imap_Client_Interaction_Pipeline), Object(Horde_Imap_Client_Interaction_Server_Tagged))\\n#1 \\\/srv\\\/ledfan.eu\\\/www\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4195): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#2 \\\/srv\\\/ledfan.eu\\\/www\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4125): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\\n#3 \\\/srv\\\/ledfan.eu\\\/www\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(1648): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#4 \\\/srv\\\/ledfan.eu\\\/www\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(1724): Horde_Imap_Client_Socket->_status(Array, 63)\\n#5 \\\/srv\\\/ledfan.eu\\\/www\\\/apps\\\/mail\\\/lib\\\/account.php(216): Horde_Imap_Client_Base->status(Array)\\n#6 \\\/srv\\\/ledfan.eu\\\/www\\\/apps\\\/mail\\\/lib\\\/controller\\\/folderscontroller.php(62): OCA\\\\Mail\\\\Account->getListArray()\\n#7 [internal function]: OCA\\\\Mail\\\\Controller\\\\FoldersController->index()\\n#8 \\\/srv\\\/ledfan.eu\\\/www\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#9 \\\/srv\\\/ledfan.eu\\\/www\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#10 \\\/srv\\\/ledfan.eu\\\/www\\\/lib\\\/private\\\/appframework\\\/app.php(104): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#11 \\\/srv\\\/ledfan.eu\\\/www\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('FoldersControll...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#12 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#13 \\\/srv\\\/ledfan.eu\\\/www\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#14 \\\/srv\\\/ledfan.eu\\\/www\\\/lib\\\/base.php(853): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#15 \\\/srv\\\/ledfan.eu\\\/www\\\/index.php(40): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/srv\\\/ledfan.eu\\\/www\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":5005}","level":4,"time":"2015-05-06T11:11:25+00:00"}
```

![selectie_035](https://cloud.githubusercontent.com/assets/2996275/7492306/ec69b8f6-f3f2-11e4-8664-b70a54cafbd1.png)

**Comment by jancborchardt** [comment]
@LEDfan can you try deleting the account and connecting again?

Also, does it work with other accounts?

**Comment by DeepDiver1975** [comment]
> 'app.mail.imaplog.enabled' => true,

as you enabled the imap log - please see have a look for errors in there

**Comment by LEDfan** [comment]
> @LEDfan can you try deleting the account and connecting again?

I tried it several times.

> Also, does it work with other accounts?
Not sure, I can't add a new one AFAIK.

````
>> Wed, 06 May 2015 11:33:49 +0000
>> Connection to: imap://imap.zoho.com:993/
>> Server connection took 0.6564 seconds.
S: * OK svwall.zoho.com IMAP4 Server (Zoho Mail IMAP4rev1 Server version 1.0)
C: 1 CAPABILITY
S: * CAPABILITY IMAP4rev1 UNSELECT CHILDREN XLIST NAMESPACE IDLE MOVE ID AUTH=PLAIN SASL-IR UIDPLUS
S: 1 OK CAPABILITY completed
>> Command 1 took 0.1509 seconds.
C: 2 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: **)]
S: * CAPABILITY IMAP4rev1 UNSELECT CHILDREN XLIST NAMESPACE IDLE MOVE ID AUTH=PLAIN SASL-IR UIDPLUS
S: 2 OK Success
>> Command 2 took 0.1892 seconds.
C: 3 LIST "" *
S: * LIST (\HasChildren) "/" "INBOX"
S: * LIST (\Noinferiors) "/" "Drafts"
S: * LIST (\Noinferiors) "/" "Templates"
S: * LIST (\Noinferiors) "/" "Sent"
S: * LIST (\Noinferiors) "/" "Spam"
S: * LIST (\HasNoChildren) "/" "Trash"
S: * LIST (\HasNoChildren) "/" "INBOX/**"
S: * LIST (\HasNoChildren) "/" "INBOX/**"
S: * LIST (\HasNoChildren) "/" "INBOX/**"
S: * LIST (\HasNoChildren) "/" "INBOX/n**"
S: 3 OK Success
>> Command 3 took 0.1567 seconds.
C: 4 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 5 STATUS Drafts (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 6 STATUS Sent (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 7 STATUS Spam (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
C: 8 STATUS Trash (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: * STATUS "INBOX" (MESSAGES 1611 RECENT 1604 UNSEEN 5 UIDNEXT 14002 UIDVALIDITY 1)
S: 4 OK Success
>> Command 4 took 0.1569 seconds.
S: * STATUS "Drafts" (MESSAGES 5 RECENT 5 UNSEEN 0 UIDNEXT 6 UIDVALIDITY 2)
S: 5 OK Success
>> Command 5 took 0.1947 seconds.
S: * STATUS "Sent" (MESSAGES 25 RECENT 25 UNSEEN 0 UIDNEXT 26 UIDVALIDITY 3)
S: 6 OK Success
>> Command 6 took 0.1949 seconds.
S: * STATUS "Spam" (MESSAGES 8 RECENT 8 UNSEEN 8 UIDNEXT 18 UIDVALIDITY 4)
S: 7 OK Success
>> Command 7 took 0.195 seconds.
S: * STATUS "Trash" (MESSAGES 17 RECENT 17 UNSEEN 0 UIDNEXT 300 UIDVALIDITY 5)
S: 8 OK Success
>> Command 8 took 0.1952 seconds.
S: 9 NO [NONEXISTENT] STATUS failed: Folder Appstore-issues does not exist
>> Command 9 took 0.1952 seconds.
S: 10 NO [NONEXISTENT] STATUS failed: Folder Chat does not exist
S: * STATUS "Templates" (MESSAGES 0 RECENT 0 UNSEEN 0 UIDNEXT 1 UIDVALIDITY 8)
S: 27 OK Success
>> Command 27 took 0.3433 seconds.
S: 28 NO [NONEXISTENT] STATUS failed: Folder Translations does not exist
>> Command 28 took 0.3433 seconds.
C: 29 LOGOUT
S: * BYE IMAP4rev1 Server logging out
S: 29 OK Success
>> Command 29 took 0.151 seconds.
````

Note that I have many folders under "INBOX", I removed some of them.

**Comment by DeepDiver1975** [comment]
actually a duplicate https://github.com/owncloud/mail/issues/626

**Comment by LEDfan** [comment]
Indeed.
