### ISSUE TITLE
Mail body for this mail(...) could not be loaded

### ISSUE THREAD

**Issue by aer0s** [owncloud/mail#671]
Hopefully this isn't a duplicate, and is just some misconfiguration on my part. Any help or pointers would be appreciated.

__OC Version__: 8.0.3
__PHP Version__: 5.5.9
__OC Mail Version__: 0.1.3

I have the mail client pointing at our Cyrus IMAP server. It appears to iterate the mailbox tree and even read the message headers just fine. In other words I see my mailbox in the left pane and list of recent mail in the center, but when any one of those mail items is opened, on load or manually clicked, I get the following error returned via xhr call:

__Note:__ I have obfuscated the *Remote Address* it is correct.

```
Internal Server Error
The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

Technical details
Remote Address: ###.###.###.200
Request ID: 158e2ac162b4be7fc41e7ef593dc286b
Code: 0
Message: Mail body for this mail(40339) could not be loaded
File: /var/www/owncloud/apps/mail/lib/message.php
Line: 458

Trace
#0 /var/www/owncloud/apps/mail/lib/message.php(421): OCA\Mail\Message->loadBodyData(Object(Horde_Mime_Part), 1)
#1 /var/www/owncloud/apps/mail/lib/message.php(323): OCA\Mail\Message->handleTextMessage(Object(Horde_Mime_Part), 1)
#2 /var/www/owncloud/apps/mail/lib/message.php(283): OCA\Mail\Message->getPart(Object(Horde_Mime_Part), 1)
#3 /var/www/owncloud/apps/mail/lib/message.php(57): OCA\Mail\Message->loadMessageBodies()
#4 /var/www/owncloud/apps/mail/lib/mailbox.php(136): OCA\Mail\Message->__construct(Object(Horde_Imap_Client_Socket), Object(Horde_Imap_Client_Mailbox), 40339, NULL, false)
#5 /var/www/owncloud/apps/mail/lib/controller/messagescontroller.php(128): OCA\Mail\Mailbox->getMessage(40339)
#6 [internal function]: OCA\Mail\Controller\MessagesController->show(40339)
#7 /var/www/owncloud/lib/private/appframework/http/dispatcher.php(158): call_user_func_array(Array, Array)
#8 /var/www/owncloud/lib/private/appframework/http/dispatcher.php(86): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\MessagesController), 'show')
#9 /var/www/owncloud/lib/private/appframework/app.php(97): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\MessagesController), 'show')
#10 /var/www/owncloud/lib/private/appframework/routing/routeactionhandler.php(44): OC\AppFramework\App::main('MessagesControl...', 'show', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#11 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)
#12 /var/www/owncloud/lib/private/route/router.php(250): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)
#13 /var/www/owncloud/lib/base.php(782): OC\Route\Router->match('/apps/mail/acco...')
#14 /var/www/owncloud/index.php(36): OC::handleRequest()
#15 {main}
```

**Comment by jancborchardt** [comment]
@aer0s does it work with another email account, like simple Gmail or so?

@zinks- @irgendwie @wurstchristoph any idea?

**Comment by clementhk** [comment]
Mind to paste the source of your email here?

**Comment by aer0s** [comment]
I'll need to figure out how to re-configure it with a gmail account. I will do so and report the result here.

To answer the second question: it doesn't seem to have anything to do with the email itself. It will not load __any__ email body from __any__ email account, at least from our imap server, yet it does load enough of the headers to produce a list of messages. If the point of the question is driving at email content headers or sections, the example below should help.

```
Return-Path: <Agb0gBm0dQaKrw6QJvsCT2w==_1116776538602_cd0PgK4BEeOBcNSuUpqCUA==@in.constantcontact.com>
Received: from email.xxxxx.com ([unix socket])
	 by cloud (Cyrus v2.4.12-Debian-2.4.12-2) with LMTPA;
	 Mon, 18 May 2015 07:09:38 -0500
X-Sieve: CMU Sieve 2.4
Received: by email.xxxx.com (Postfix, from userid 10211)
	id 6D0782814C5; Mon, 18 May 2015 07:09:38 -0500 (CDT)
X-Spam-Checker-Version: SpamAssassin 3.3.2 (2011-06-06) on cloud.xxxx.com
X-Spam-Level: 
X-Spam-Status: No, score=-5.4 required=5.0 tests=BAYES_00,FREEMAIL_FROM,
	HTML_MESSAGE,RCVD_IN_DNSWL_NONE,RCVD_IN_IADB_DK,RCVD_IN_IADB_LISTED,
	RCVD_IN_IADB_OPTIN,RCVD_IN_IADB_RDNS,RCVD_IN_IADB_SENDERID,RCVD_IN_IADB_SPF,
	RCVD_IN_IADB_VOUCHED,T_DKIM_INVALID,T_FILL_THIS_FORM_SHORT,
	T_TO_NO_BRKTS_FREEMAIL,T_URIBL_SEM,T_URIBL_SEM_RED,URI_NOVOWEL autolearn=ham
	version=3.3.2
Received: from spamfilter.xxxx.com (unknown [xxx.xxx.xxx.233])
	by email.xxxx.com (Postfix) with ESMTP id 6E0AD280361
	for <jinoll@xxxx.com>; Mon, 18 May 2015 07:09:34 -0500 (CDT)
X-ASG-Debug-ID: 1431950931-01c9c506db227ec0001-UCe4g0
Received: from ccm36.constantcontact.com (ccm36.constantcontact.com [208.75.123.196]) by spamfilter.xxxx.com with ESMTP id v5Ic113htqRz4S1n for <jinoll@xxxx.com>; Mon, 18 May 2015 07:08:51 -0500 (CDT)
X-Barracuda-Envelope-From: Agb0gBm0dQaKrw6QJvsCT2w==_1116776538602_cd0PgK4BEeOBcNSuUpqCUA==@in.constantcontact.com
X-Barracuda-IPDD: Level1 [in.constantcontact.com/208.75.123.196]
X-Barracuda-Registry: Level1 [in.constantcontact.com/208.75.123.196]
X-Barracuda-Apparent-Source-IP: 208.75.123.196
Received: from p2-jbsvcs5291.ad.prodcc.net (p2-pen7.ad.prodcc.net [10.252.0.107])
	by p2-mail189.ccm36.constantcontact.com (Postfix) with ESMTP id 625B2A8D72C
	for <jinoll@xxxx.com>; Mon, 18 May 2015 08:08:51 -0400 (EDT)
DKIM-Signature: v=1; q=dns/txt; a=rsa-sha256; c=relaxed/relaxed; s=1000073432; d=auth.ccsend.com; h=to:X-Feedback-ID:subject:mime-version:message-id:from:date:list-unsubscribe:reply-to; bh=677C37qfp6yBymkSjMdOhOIEwR9LHEyubncKBU/aqXk=; b=TR1c7d+jG527j3br7ayCGCrtWSgGmvl5d8WkCzH6gLrENNxRO1dgbKasGvgCQIIkmWDETH+oMMMXpdHjxH5q3tLrDiBTns4MCkn5gPFyv1lrupRxRuD73w+X+tMbQMfo8Pk9KVGz2tktdiGlviFMP5/w3EAJrIHrytKgELWcyfs=
Message-ID: <1120997722910.1116776538602.2107307358.0.540808JL.1002@scheduler.constantcontact.com>
Date: Mon, 18 May 2015 08:08:51 -0400 (EDT)
From: GSLBAA <gslbaa.president@gmail.com>
Reply-To: gslbaa.president@gmail.com
To: jinoll@xxxx.com
Subject: News from GSLBAA
Cc: 
X-ASG-Orig-Subj: News from GSLBAA
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_303787479_193590191.1431950931385"
List-Unsubscribe: http://visitor.constantcontact.com/do?p=un&m=001kvN2wONSjdiqZO5JBXRnIQ%3D%3D&se=001Hte-Ji-UQJfSi-jJUydvFg%3D%3D&t=001EkZLEx15CcE%3D&llr=kpidrcqab
X-Campaign-Activity-ID: 81bd2006-6d1d-41a2-abc3-a409bec093db
X-Channel-ID: 71dd0f80-ae01-11e3-8170-d4ae529a8250
X-Mailer: Roving Constant Contact 2012 (http://www.constantcontact.com)
X-Return-Path-Hint: Agb0gBm0dQaKrw6QJvsCT2w==_1116776538602_cd0PgK4BEeOBcNSuUpqCUA==@in.constantcontact.com
X-Roving-Campaignid: 1120997722910
X-Roving-Id: 1116776538602.2107307358
X-Feedback-ID: 71dd0f80-ae01-11e3-8170-d4ae529a8250:81bd2006-6d1d-41a2-abc3-a409bec093db:1116776538602:CTCT
X-CTCT-ID: 6f9fa2a0-ae01-11e3-807e-d4ae529a8250
X-Barracuda-Connect: ccm36.constantcontact.com[208.75.123.196]
X-Barracuda-Start-Time: 1431950931
X-Barracuda-URL: http://10.10.11.233:8000/cgi-mod/mark.cgi
X-Barracuda-BRTS-Status: 1
X-Barracuda-BRTS-Evidence: gatewaypilots.org
X-Virus-Scanned: by bsmtpd at xxxx.com
X-Barracuda-Spam-Score: 0.50
X-Barracuda-Spam-Status: No, SCORE=0.50 using global scores of TAG_LEVEL=3.5 QUARANTINE_LEVEL=1000.0 KILL_LEVEL=5.0 tests=HTML_MESSAGE, URI_NOVOWEL
X-Barracuda-Spam-Report: Code version 3.2, rules version 3.2.3.19052
	Rule breakdown below
	 pts rule name              description
	---- ---------------------- --------------------------------------------------
	0.50 URI_NOVOWEL            URI: URI hostname has long non-vowel sequence
	0.00 HTML_MESSAGE           BODY: HTML included in message

------=_Part_303787479_193590191.1431950931385
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

================================================
|   Plain Text Content Truncated for brevity   |
================================================

------=_Part_303787479_193590191.1431950931385

Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

================================================
|      HTML Content Truncated for brevity      |
================================================

------=_Part_303787479_193590191.1431950931385--

```

**Comment by jancborchardt** [comment]
@clementhk did that shed any light on the issue?

@aer0s does the issue still occur?

**Comment by jancborchardt** [comment]
@DeepDiver1975 check it out.

**Comment by aer0s** [comment]
Problem still exists and no the results above don't provide much in terms of pinpointing the issue.

**Comment by clementhk** [comment]
http://osdir.com/ml/horde/2014-09/msg00196.html
http://osdir.com/ml/horde/2014-09/msg00198.html

**Comment by clementhk** [comment]
Looks like a horde problem, if I can find a way to replicate it then I will check upstream code.

**Comment by clementhk** [comment]
https://github.com/horde/horde/blob/3aff0b0dfcfb190e307b3dc01edfa87d4baaacc9/framework/Imap_Client/lib/Horde/Imap/Client/Socket/Connection/Socket.php#L211

**Comment by ChristophWurst** [comment]
@aer0s I'm closing this issue due to inactivity. Please re-open if you still face those problems. Thanks.
