### ISSUE TITLE
"Error while loading the selected account."

### ISSUE THREAD

**Issue by rigrig** [owncloud/mail#720]
Setting up my account seems to work, but after that it won't even display the mail interface.

### Steps to reproduce
1. Enable the Mail app
2. Setup a new mail account (IMAP & SMTP both localhost over TLS)

### Expected behaviour
Mail interface shows up

### Actual behaviour
Interface stays empty, except for a single throbber image
Two other throbbers show up at first, but are hidden after a few seconds
The standard OwnCloud top bar is present, and displays the message "Error while loading the selected account."

### Server configuration
OS: Debian 7.8;  Linux tubul.tubul.net 3.2.0-4-amd64 #1 SMP Debian 3.2.41-2+deb7u2 x86_64 GNU/Linux
Web server: Apache/2.2.22 (Debian), built:   Dec 23 2014 22:48:29
Database: mysqld  Ver 5.5.43-MariaDB-1~wheezy-log for debian-linux-gnu on x86_64 (mariadb.org binary distribution)
PHP 5.4.39-0+deb7u2 (cli) (built: Mar 25 2015 08:33:29)
ownCloud 8.0.3 (stable) 
Updated from an older ownCloud (since version 7.something)

#### Apps:
Enabled:
 - calendar
 - contacts
 - external
 - files
 - files_external
 - files_locking
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
 - mail
 - mozilla_sync
 - news
 - notes
 - tasks
 - updater

Disabled:
 - activity
 - documents
 - files_encryption
 - files_tree
 - music
 - provisioning_api
 - search_lucene
 - shorty
 - templateeditor
 - user_external
 - user_ldap
 - user_webdavauth

#### Content of config/config.php:
```
<?php
$CONFIG = array (
  'instanceid' => 'ocaed749a93a',
  'passwordsalt' => '**redacted**',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'installed' => true,
  'forcessl' => true,
  'loglevel' => 2,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'cloud.tubul.net',
    1 => 'public.tubul.net',
    2 => 'tubul.net',
  ),
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbuser' => 'owncloud',
  'dbpassword' => '**redacted**',
  'secret' => '**redacted**',
  'forceSSLforSubdomains' => true,
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'tubul.net',
  'updatechecker' => false,
  'appstoreenabled' => true,
  'appstoreurl' => 'https://api.owncloud.com/v1',
);
```
No external storage
Encryption disabled
No external user-backend

### Client configuration
Mozilla Firefox 38.0.1
Operating system: LMDE 2
Linux vimes 4.0-4.dmz.1-liquorix-amd64 #1 ZEN SMP PREEMPT Debian 4.0-8 (2015-05-17) x86_64 GNU/Linux

#### Error in ownCloud log
```
Exception: {"Message":"HMAC does not match.","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/mail\/lib\/account.php(86): OC\\Security\\Crypto->decrypt('a394efdfa53bc6e...')\n#1 \/var\/www\/owncloud\/apps\/mail\/lib\/account.php(153): OCA\\Mail\\Account->getImapConnection()\n#2 \/var\/www\/owncloud\/apps\/mail\/lib\/account.php(196): OCA\\Mail\\Account->listMailboxes()\n#3 \/var\/www\/owncloud\/apps\/mail\/lib\/account.php(210): OCA\\Mail\\Account->getMailboxes()\n#4 \/var\/www\/owncloud\/apps\/mail\/lib\/controller\/folderscontroller.php(62): OCA\\Mail\\Account->getListArray()\n#5 [internal function]: OCA\\Mail\\Controller\\FoldersController->index()\n#6 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(158): call_user_func_array(Array, Array)\n#7 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(86): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Mail\\Controller\\FoldersController), 'index')\n#8 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Mail\\Controller\\FoldersController), 'index')\n#9 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('FoldersControll...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#11 \/var\/www\/owncloud\/lib\/private\/route\/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#12 \/var\/www\/owncloud\/lib\/base.php(782): OC\\Route\\Router->match('\/apps\/mail\/acco...')\n#13 \/var\/www\/owncloud\/index.php(36): OC::handleRequest()\n#14 {main}","File":"\/var\/www\/owncloud\/lib\/private\/security\/crypto.php","Line":109} 
```

#### Browser log
Not sure if this can be dumped from Firefox?, last two entries in the debugger network panel:
https://cloud.tubul.net/index.php/apps/mail/accounts returns 200, contains my account info
https://cloud.tubul.net/index.php/apps/mail/accounts/1/folders returns 500  contains an OwnCloud error page

**Comment by wurstchristoph** [comment]
@rigrig is this a fresh install of the mail app or have you used an older version before?

It seems like the exception is thrown because the IMAP password can not be decrypted.

**Comment by rigrig** [comment]
I tried it for the first time about a week ago, IIRC it gave the same error then, but I didn't have time to file a proper bug report. I did follow the 'Resetting the app' instructions though.

Today (to make sure):
- deleted the apps/mail folder
- in mysql, confirmed the rows & table for the mail app were present, ran
```sql
use owncloud;
DELETE FROM oc_appconfig WHERE appid = 'mail';
DROP TABLE oc_mail_accounts;
``` 
  then checked those rows & table were now gone

- in the F12-console, ran 
```js
localStorage.clear();
```
- reproduced the bug as described above

**Comment by LukasReschke** [comment]
Would there by any possibility that you can give us the the `inbound_password` stored in the database? – If so please use a dummy account and not your real credentials. Though this password is encrypted with your secret defined in config.php but better be safe than sorry ;)

**Comment by LukasReschke** [comment]
It should look like the following scheme:

```
7ed8455e7486af5b19c450cbb9d0ed08|uuhw9f193QnqwbOV|ad57a372b1e630dd7724f3b5152c0f092df405933a5da244ca06eae237d9aeb57457b4e87e39008b69612a115df8d01defc543f2e9832de24ee522a0c0cf41dd
```

**Comment by rigrig** [comment]
Apparently this is caused by my password length:
* Freshly reinstalled mail app
* Changed my account password to `test123`   
  -> mail app worked fine
* Deleted mail account in the app
* Changed my password to `ZCMisWk3fKsSxnoqi3BXBERZbjxKBJMb9xeQyqMSvwLrXY7BaSRe5sH9oLTXHuXA`   
  (As my real password also consists of 64 random alphanumerics)   
  -> problem reappeared   
  `inbound_password` is `6b37f99ad422d56579fb5276e787625e8d66b79e484d844f9b13dbbc988730774c2bf7ac8d3ebc36b062863e91736a0408594008080678d6d076d70eff8604831b0083dba26db8a0a9c7d7ba69536f10|9MPPsAjGTdt.ANk9|06a66ea8158bc9b2c5e6cda53ef3248ba32f79f850199abb56c6e52ef54b8cf8d564e99635412`

I tested with some other passwords:
```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab -> works
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac -> fails
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab -> fails
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabc -> works
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabq -> works
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab -> works
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1 -> fails
123456789012345678901234567890123456789012345678901234567890
         1         2         3         4         5
```

It seems passwords up to a length of 47 characters work fine, and passwords of 48 or more characters cause the bug to happen.

My `inbound_password` seems to be longer than your example, and is in fact exactly 255 characters long. As `inbound_password` is a `varchar(255)`, I suspect the encrypted version of my password is cut off when saved to the database, causing the decryption error when reading it back.

**Comment by LukasReschke** [comment]
> My inbound_password seems to be longer than your example, and is in fact exactly 255 characters long. As inbound_password is a varchar(255), I suspect the encrypted version of my password is cut off when saved to the database, causing the decryption error when reading it back.

Very nice catch. 

cc @DeepDiver1975 Shall we change the type of the field or how shall we handle this best?

**Comment by rigrig** [comment]
I just confirmed:
```sql
alter table oc_mail_accounts change column inbound_password inbound_password varchar(65535) not null; 
alter table oc_mail_accounts change column outbound_password outbound_password varchar(65535) null;
```
Fixed the issue for me, the stored ```inbound_password``` value is now 306 characters long.

**Comment by jancborchardt** [comment]
@rigrig or @LukasReschke can you open a pull request to fix this?

**Comment by DeepDiver1975** [comment]
We actually need both: more chars in password fields and double check length on change/insert

**Comment by rigrig** [comment]
I only altered the database on my server directly, haven't actually looked at the code.
So while I might get around to creating a pull request eventually, it will take quite some time for me to get started with the OC code first.

It looks like a simple change to <length> in ```appinfo/database.xml``` should do the trick, but I have no idea what would be a reasonable length, how migrations work in OC, and whether setting the length to something over 255 could break some databases.

**Comment by DeepDiver1975** [comment]
Changing database.xml is one thing. In addition the version in info.xml and appinfo/version have to be incremented. 

Regarding migration testing:  thats going to be tricky as I want this to be unit tested. You can leave this to me :wink:

**Comment by jancborchardt** [comment]
@LukasReschke dooo it!

**Comment by jancborchardt** [comment]
@LukasReschke @DeepDiver1975 I will move this to 0.3
