### ISSUE TITLE
Task create throws fatal error

### ISSUE THREAD

**Issue by mradke** [owncloud/mail#722]
I am trying to get the Task-App up and running on my server behind an nginx and on an owncloud distribution package installation (running Ubuntu). The installation is secured with a self signed root certificate.

**Expected behaviour**
* Install the app
* Activate the app
* Create new list
* Create new task (type in the textfield, press return)

**Obeserved behaviour**
* Install the app - ok
* Activate the app - ok
* Create new list - ok
* Create new task - 500/internal server error thrown in the client console + nothing happens

The following is logged in the Owncloud admin log:
```
Exception: {"Message":"You must pass a \\Sabre\\VObject\\Component, \\Sabre\\VObject\\Property or scalar type","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/tasks\/controller\/helper.php(231): Sabre\\VObject\\Component->__set('CREATED', Object(DateTime))\n#1 \/var\/www\/owncloud\/apps\/tasks\/controller\/taskscontroller.php(294): OCA\\Tasks\\Controller\\Helper::createVCalendarFromRequest(Array)\n#2 [internal function]: OCA\\Tasks\\Controller\\TasksController->addTask()\n#3 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(158): call_user_func_array(Array, Array)\n#4 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(86): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Tasks\\Controller\\TasksController), 'addTask')\n#5 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Tasks\\Controller\\TasksController), 'addTask')\n#6 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('TasksController', 'addTask', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#7 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#8 \/var\/www\/owncloud\/lib\/private\/route\/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#9 \/var\/www\/owncloud\/lib\/base.php(782): OC\\Route\\Router->match('\/apps\/tasks\/tas...')\n#10 \/var\/www\/owncloud\/index.php(36): OC::handleRequest()\n#11 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Sabre\/VObject\/Component.php","Line":365}
```

Is this a known issue? Am I missing something?

**Comment by mradke** [comment]
sorry - wrong board :-1: :-/
