### ISSUE TITLE
500 on IMAP server issue

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#924]
OC log:

Fatal 	index 	Exception: {"Exception":"Horde_Imap_Client_Exception","Message":"Mail server closed the connection unexpectedly.","Code":4,"Trace":"#0 \/owncloud-8.1.0\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(4436): Horde_Imap_Client_Socket_Connection_Socket->read()\n#1 \/owncloud-8.1.0\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(4208): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\n#2 \/owncloud-8.1.0\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(4136): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\n#3 \/owncloud-8.1.0\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(231): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Command))\n#4 \/owncloud-8.1.0\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Base.php(647): Horde_Imap_Client_Socket->_initCapability()\n#5 \/owncloud-8.1.0\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(607): Horde_Imap_Client_Base->_capability('IMAP4REV1')\n#6 \/owncloud-8.1.0\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(374): Horde_Imap_Client_Socket->_connect()\n#7 \/owncloud-8.1.0\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Base.php(831): Horde_Imap_Client_Socket->_login()\n#8 \/owncloud-8.1.0\/apps\/mail\/lib\/account.php(114): Horde_Imap_Client_Base->login()\n#9 \/owncloud-8.1.0\/apps\/mail\/lib\/account.php(180): OCA\\Mail\\Account->getImapConnection()\n#10 \/owncloud-8.1.0\/apps\/mail\/lib\/controller\/messagescontroller.php(325): OCA\\Mail\\Account->getMailbox('INBOX')\n#11 \/owncloud-8.1.0\/apps\/mail\/lib\/controller\/messagescontroller.php(134): OCA\\Mail\\Controller\\MessagesController->getFolder(4, 'SU5CT1g=')\n#12 [internal function]: OCA\\Mail\\Controller\\MessagesController->show(4, 'SU5CT1g=', '46')\n#13 \/owncloud-8.1.0\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#14 \/owncloud-8.1.0\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Mail\\Controller\\MessagesController), 'show')\n#15 \/owncloud-8.1.0\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Mail\\Controller\\MessagesController), 'show')\n#16 \/owncloud-8.1.0\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('MessagesControl...', 'show', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#17 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#18 \/owncloud-8.1.0\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#19 \/owncloud-8.1.0\/lib\/base.php(867): OC\\Route\\Router->match('\/apps\/mail\/acco...')\n#20 \/owncloud-8.1.0\/index.php(40): OC::handleRequest()\n#21 {main}","File":"\/owncloud-8.1.0\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket\/Connection\/Socket.php","Line":147} 	2015-08-07T03:40:22+08:00

Error 	PHP 	fgets(): SSL operation failed with code 1. OpenSSL Error messages: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac at /owncloud-8.1.0/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket/Connection/Socket.php#156 	2015-08-07T03:40:21+08:00

**Comment by aspdye** [comment]
Please follow the issue template so we get the info we need to be able to debug and fix the problem:
https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by PoPoutdoor** [comment]
The point is error from Horde is not handled.

In case of IMAP server issue, show error message with 503 seems more proper than 500.

**Comment by agowa338** [comment]
### Steps to reproduce
1. Add imap Account

### Expected behaviour
Load all Folders and show the E-Mails

### Actual behaviour
Endless Loading and in the Webconsole I get the Error:
https://server.domain.de:8443/index.php/apps/mail/accounts/2/folders Failed to load resource: the server responded with a status of 500 (Internal Server Error)
mail.js?v=7d4ad60ce28afe28c2d10f6329835e6c:347 Uncaught TypeError: Cannot read property 'get' of undefined(anonymous function) @ mail.js?v=7d4ad60ce28afe28c2d10f6329835e6c:347_.each._.forEach @ underscore.js?v=7d4ad60ce28afe28c2d10f6329835e6c:79Mail.BackGround.checkForNotifications @ mail.js?v=7d4ad60ce28afe28c2d10f6329835e6c:345

### Server configuration
**Operating system**:
Ubuntu

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
8.1.1 (stable)

**Updated from an older ownCloud or fresh install:**
Fresh installed a view weeks ago.

**List of activated apps:**
Activity
Default encryption module
Deleted files
Documents
File Locking
First Run Wizard
LDAP user and group backend
Mail Template Editor
PDF Viewer
Pictures
Provisioning API
Share Files
Text Editor
Updater
Versions
Video Viewer
Calendar
Mail


**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP
#### LDAP configuration (delete this part if not used)

```
On ownCloud 7+ with access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder


### Client configuration
**Browsers:**
Chrome 44
IE 11
**Operating system:**
Windows 8.1
Windows 7
### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
Tracer created
GET https://server.domain.local:8443/index.php/apps/mail/accounts/2/folders 500 (Internal Server Error)

b) The network log 
GET "https://server.domain.de:8443/index.php/apps/mail/accounts/2/folders" => Status 500

**Comment by ChristophWurst** [comment]
Due to no activity for almost a year, I am closing this issue now. Please re-open if the error still occurs. Thanks
