### ISSUE TITLE
Account not loaded

### ISSUE THREAD

**Issue by PoPoutdoor** [owncloud/mail#962]
Similar entries been logged for a while, affected Mail service provider includes:

- Outlook.com(@hotmail acount)
- Mail.ru(@icqmail account)

This is a bad user experience when mail account not loaded silently.

Can we have some kind of status on the left sidebar to indicate server side issue of specified mail account?

OC 8.1.0.8
mail master 569c42da2498e30289e9b60eaf903c42dc7bb564

OC log:
gets(): SSL: Connection reset by peer at /owncloud-8.1.0/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket/Connection/Socket.php#156 

Exception: {"Exception":"Horde_Imap_Client_Exception","Message":"Mail server closed the connection unexpectedly.","Code":4,"Trace":"

```
#0 \/owncloud-8.1.0\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(4436): Horde_Imap_Client_Socket_Connection_Socket->read()
#1 \/owncloud-8.1.0\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(4208): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))
#2 \/owncloud-8.1.0\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(4136): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)
#3 \/owncloud-8.1.0\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(1656): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))
#4 \/owncloud-8.1.0\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Base.php(1724): Horde_Imap_Client_Socket->_status(Array, 1)
#5 \/owncloud-8.1.0\/apps\/mail\/lib\/mailbox.php(151): Horde_Imap_Client_Base->status(Object(Horde_Imap_Client_Mailbox), 1)
#6 \/owncloud-8.1.0\/apps\/mail\/lib\/mailbox.php(158): OCA\\Mail\\Mailbox->getStatus(1)
#7 \/owncloud-8.1.0\/apps\/mail\/lib\/account.php(405): OCA\\Mail\\Mailbox->getTotalMessages()
#8 \/owncloud-8.1.0\/apps\/mail\/lib\/account.php(435): OCA\\Mail\\Account->guessBestMailBox(Array)
#9 \/owncloud-8.1.0\/apps\/mail\/lib\/account.php(272): OCA\\Mail\\Account->getSpecialFolder('trash', true)
#10 \/owncloud-8.1.0\/apps\/mail\/lib\/account.php(230): OCA\\Mail\\Account->getSpecialFoldersIds()
#11 \/owncloud-8.1.0\/apps\/mail\/lib\/controller\/folderscontroller.php(60): OCA\\Mail\\Account->getListArray()
#12 [internal function]: OCA\\Mail\\Controller\\FoldersController->index()
#13 \/owncloud-8.1.0\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)
#14 \/owncloud-8.1.0\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Mail\\Controller\\FoldersController), 'index')
#15 \/owncloud-8.1.0\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Mail\\Controller\\FoldersController), 'index')
#16 \/owncloud-8.1.0\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('FoldersControll...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)
#17 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)
#18 \/owncloud-8.1.0\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)
#19 \/owncloud-8.1.0\/lib\/base.php(867): OC\\Route\\Router->match('\/apps\/mail\/acco...')
#20 \/owncloud-8.1.0\/index.php(40): OC::handleRequest()
#21 {main}","File":"\/owncloud-8.1.0\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket\/Connection\/Socket.php","Line":147} 
```

**Comment by ChristophWurst** [comment]
@PoPoutdoor please try the brand-new owncloud mail 0.4. Hopefully that has been fixed by updating our horde libs. Re-open if you still face that problem, thanks.
